import { blogPosts, type BlogPost } from '@/lib/blog-posts';
import type { Language } from '@/hooks/use-language';

type ArticleText = Pick<BlogPost, 'titulo' | 'descricao' | 'conteudo'>;

const articles: Record<Exclude<Language, 'pt'>, Record<string, ArticleText>> = {
  en: {
    'sink-roll-como-escolher-liga': { titulo: 'Sink Roll: choosing an alloy for galvanizing lines', descricao: 'Evaluate the bath, temperature, assembly geometry and operating history before specifying a Sink Roll alloy.', conteudo: `<p>A <strong>Sink Roll</strong> operates submerged in the zinc pot of a hot-dip galvanizing line. Its specification must account for the bath composition and temperature, the assembly geometry, mechanical loads and operating history.</p><h2>Selection criteria</h2><ul><li>Bath composition and temperature.</li><li>Line geometry, speed and roll-end design.</li><li>Wear, maintenance and previous failures.</li></ul><p>Aceros supplies Sink Rolls, roll-end bushings, arms, snouts and assembled units to customer drawings. The material is selected for the actual application, rather than by a single general rule.</p><h2>Manufacturing and inspection</h2><p>The project may combine centrifugal casting, machining, chemical analysis, hardness testing, ultrasound and dimensional inspection according to the supply requirements.</p>` },
    'astm-a297-hk-hh-hp-diferencas': { titulo: 'ASTM A297: differences between HH, HK and HP grades', descricao: 'An overview of the heat-resistant cast steel grades HH, HK and HP and their typical industrial applications.', conteudo: `<p><strong>ASTM A297</strong> covers heat-resistant cast steels with different chromium and nickel contents. HH, HK and HP must be evaluated against the drawing, service temperature, furnace atmosphere and operating cycle.</p><h2>Typical applications</h2><p>HH may be considered for heat-treatment furnace components; HK is used in various industrial furnace parts; HP is commonly specified for reformer tubes. The appropriate grade depends on the complete service conditions.</p><h2>Technical specification</h2><p>Aceros reviews temperature, atmosphere, thermal cycles and application history. Reference values do not replace the applicable standard edition, project requirements or the final technical specification.</p>` },
    'fundicao-centrifugada-vantagens': { titulo: 'Centrifugal casting: benefits and when to use it', descricao: 'How centrifugal casting forms tubular parts and when static casting may be more suitable.', conteudo: `<p>In <strong>centrifugal casting</strong>, molten steel is poured into a preheated rotating mold. Centrifugal force drives the metal toward the mold wall, forming a tubular part.</p><h2>Benefits for tubular components</h2><p>The process supports dense walls and concentric internal and external diameters. Subsequent machining brings the component to the dimensions and tolerances specified in the drawing. Rotation, mold diameter and part mass are set for each project.</p><h2>When static casting is appropriate</h2><p>Static casting may be selected for geometries that cannot be centrifuged, including complex housings and asymmetric components. Aceros engineering evaluates the suitable process for each part.</p>` },
    'bucha-bimetalica-sink-roll': { titulo: 'Sink Roll bushings: specification and manufacturing criteria', descricao: 'Information needed to specify a Sink Roll end bushing for a galvanizing line.', conteudo: `<p>The <strong>Sink Roll end bushing</strong> is part of an assembly operating in a hot-dip galvanizing pot. Material, dimensions, finish and tolerances must follow the drawing and service conditions.</p><h2>Information to review</h2><ul><li>Drawings and dimensions of the roll end, bushing and related parts.</li><li>Bath, temperature, loads and wear history.</li><li>Current material and available failure or maintenance records.</li></ul><h2>Aceros manufacturing</h2><p>Aceros manufactures bushings by centrifugal casting and machines them to drawing. Depending on the project, inspection may include chemical analysis, hardness, ultrasound and dimensional checks.</p>` },
    'ligas-304-316-310-alta-temperatura': { titulo: '304, 316 and 310 stainless steels at high temperature', descricao: 'Compare three stainless steel grades by composition, corrosion resistance and typical applications.', conteudo: `<p><strong>304, 316 and 310</strong> are austenitic stainless steels, but their alloy content and typical uses differ.</p><h2>Comparing the grades</h2><p>304 is a common general-purpose stainless steel. 316 contains molybdenum, which improves resistance in many chloride-containing environments. 310 has higher chromium and nickel content and is often considered for high-temperature oxidation resistance.</p><h2>Choosing for the application</h2><p>Temperature alone is not enough: atmosphere, loads, corrosion, cycles and the applicable standard also matter. More demanding high-temperature service may require evaluation of an ASTM A297 cast grade. Reference temperatures do not replace project-specific engineering.</p>` },
  },
  es: {
    'sink-roll-como-escolher-liga': { titulo: 'Sink Roll: cómo elegir la aleación para líneas de galvanizado', descricao: 'Evalúe el baño, la temperatura, la geometría del conjunto y el historial operativo antes de especificar la aleación.', conteudo: `<p>El <strong>Sink Roll</strong> trabaja sumergido en el baño de zinc de una línea de galvanizado en caliente. Su especificación debe considerar la composición y temperatura del baño, la geometría, las cargas y el historial operativo.</p><h2>Criterios de selección</h2><ul><li>Composición y temperatura del baño.</li><li>Geometría, velocidad de la línea y diseño de las puntas.</li><li>Desgaste, mantenimiento y fallas anteriores.</li></ul><p>Aceros suministra Sink Rolls, bujes, brazos, snouts y conjuntos montados según el plano del cliente. El material se elige para la aplicación real.</p><h2>Fabricación y control</h2><p>El proyecto puede incluir fundición centrífuga, mecanizado, análisis químico, dureza, ultrasonido y control dimensional según los requisitos del suministro.</p>` },
    'astm-a297-hk-hh-hp-diferencas': { titulo: 'ASTM A297: diferencias entre los grados HH, HK y HP', descricao: 'Panorama de los aceros fundidos resistentes al calor HH, HK y HP y sus aplicaciones típicas.', conteudo: `<p>La norma <strong>ASTM A297</strong> incluye aceros fundidos resistentes al calor con diferentes contenidos de cromo y níquel. HH, HK y HP deben evaluarse según el plano, la temperatura, la atmósfera y el régimen operativo.</p><h2>Aplicaciones típicas</h2><p>HH puede emplearse en componentes de hornos de tratamiento térmico; HK en diversas piezas de hornos industriales; HP se especifica con frecuencia para tubos de reformadores. La elección depende de las condiciones completas de servicio.</p><h2>Especificación técnica</h2><p>Aceros analiza temperatura, atmósfera, ciclos térmicos e historial de aplicación. Los valores de referencia no sustituyen la edición aplicable de la norma ni la especificación final del proyecto.</p>` },
    'fundicao-centrifugada-vantagens': { titulo: 'Fundición centrífuga: ventajas y cuándo utilizarla', descricao: 'Cómo se forman piezas tubulares por centrifugación y cuándo conviene la fundición estática.', conteudo: `<p>En la <strong>fundición centrífuga</strong>, el acero líquido se vierte en un molde precalentado y en rotación. La fuerza centrífuga dirige el metal hacia la pared y forma una pieza tubular.</p><h2>Ventajas para componentes tubulares</h2><p>El proceso favorece paredes densas y diámetros interior y exterior concéntricos. El mecanizado posterior permite cumplir las dimensiones y tolerancias del plano. La rotación, el diámetro del molde y la masa se definen para cada proyecto.</p><h2>Cuándo usar fundición estática</h2><p>Puede seleccionarse para geometrías que no admiten centrifugación, como carcasas complejas y piezas asimétricas. La ingeniería de Aceros evalúa el proceso adecuado.</p>` },
    'bucha-bimetalica-sink-roll': { titulo: 'Bujes para Sink Roll: criterios de especificación y fabricación', descricao: 'Datos necesarios para especificar un buje de punta de Sink Roll en una línea de galvanizado.', conteudo: `<p>El <strong>buje de punta del Sink Roll</strong> integra un conjunto que trabaja en el baño de galvanizado en caliente. Material, dimensiones, acabado y tolerancias deben seguir el plano y las condiciones reales.</p><h2>Datos que se deben revisar</h2><ul><li>Planos y dimensiones de la punta, el buje y las piezas asociadas.</li><li>Baño, temperatura, cargas e historial de desgaste.</li><li>Material actual y registros de fallas o mantenimiento.</li></ul><h2>Fabricación Aceros</h2><p>Aceros fabrica bujes por fundición centrífuga y los mecaniza según plano. El control puede incluir análisis químico, dureza, ultrasonido e inspección dimensional.</p>` },
    'ligas-304-316-310-alta-temperatura': { titulo: 'Aceros inoxidables 304, 316 y 310 a alta temperatura', descricao: 'Comparación de composición, resistencia a la corrosión y aplicaciones típicas.', conteudo: `<p><strong>304, 316 y 310</strong> son aceros inoxidables austeníticos, pero difieren en contenido de aleantes y aplicaciones.</p><h2>Comparación de los grados</h2><p>304 es un acero inoxidable de uso general. 316 contiene molibdeno, que mejora la resistencia en muchos ambientes con cloruros. 310 tiene más cromo y níquel y suele considerarse por su resistencia a la oxidación a alta temperatura.</p><h2>Elección para la aplicación</h2><p>No basta con conocer la temperatura: también importan la atmósfera, las cargas, la corrosión, los ciclos y la norma aplicable. En servicios más exigentes puede evaluarse un grado fundido ASTM A297. Las temperaturas de referencia no sustituyen el análisis del proyecto.</p>` },
  },
  de: {
    'sink-roll-como-escolher-liga': { titulo: 'Sink Roll: Legierung für Verzinkungslinien auswählen', descricao: 'Bad, Temperatur, Baugruppengeometrie und Betriebshistorie vor der Legierungsauswahl bewerten.', conteudo: `<p>Eine <strong>Sink Roll</strong> arbeitet im Zinkbad einer Feuerverzinkungslinie. Bei der Spezifikation sind Badzusammensetzung und Temperatur, Geometrie, mechanische Belastung und Betriebshistorie zu berücksichtigen.</p><h2>Auswahlkriterien</h2><ul><li>Zusammensetzung und Temperatur des Bads.</li><li>Geometrie, Liniengeschwindigkeit und Rollenzapfen.</li><li>Verschleiß, Wartung und frühere Ausfälle.</li></ul><p>Aceros liefert Sink Rolls, Endbuchsen, Arme, Snouts und Baugruppen nach Kundenzeichnung. Der Werkstoff wird für die tatsächliche Anwendung ausgewählt.</p><h2>Fertigung und Prüfung</h2><p>Je nach Projekt gehören Schleuderguss, Bearbeitung, chemische Analyse, Härteprüfung, Ultraschall und Maßprüfung zum Lieferumfang.</p>` },
    'astm-a297-hk-hh-hp-diferencas': { titulo: 'ASTM A297: Unterschiede zwischen HH, HK und HP', descricao: 'Überblick über die hitzebeständigen Stahlguss-Sorten HH, HK und HP und typische Anwendungen.', conteudo: `<p><strong>ASTM A297</strong> umfasst hitzebeständige Stahlguss-Sorten mit unterschiedlichem Chrom- und Nickelgehalt. HH, HK und HP sind anhand von Zeichnung, Temperatur, Ofenatmosphäre und Betriebszyklus zu bewerten.</p><h2>Typische Anwendungen</h2><p>HH kann für Bauteile von Wärmebehandlungsöfen in Betracht kommen; HK wird für verschiedene Industrieofenbauteile eingesetzt; HP wird häufig für Reformerrohre spezifiziert. Die Auswahl hängt von den gesamten Betriebsbedingungen ab.</p><h2>Technische Spezifikation</h2><p>Aceros prüft Temperatur, Atmosphäre, thermische Zyklen und Anwendungshistorie. Richtwerte ersetzen weder die gültige Normausgabe noch die endgültige Projektspezifikation.</p>` },
    'fundicao-centrifugada-vantagens': { titulo: 'Schleuderguss: Vorteile und Einsatzbereiche', descricao: 'Wie Schleuderguss rohrförmige Teile formt und wann statischer Guss besser geeignet ist.', conteudo: `<p>Beim <strong>Schleuderguss</strong> wird flüssiger Stahl in eine vorgewärmte rotierende Form gegossen. Die Fliehkraft drückt das Metall an die Formwand und bildet ein rohrförmiges Bauteil.</p><h2>Vorteile für Rohrbauteile</h2><p>Das Verfahren begünstigt dichte Wände sowie konzentrische Innen- und Außendurchmesser. Anschließende Bearbeitung erreicht die Maße und Toleranzen der Zeichnung. Drehzahl, Formdurchmesser und Masse werden projektspezifisch festgelegt.</p><h2>Wann statischer Guss passt</h2><p>Für nicht schleudergießbare Geometrien wie komplexe Gehäuse und asymmetrische Teile kann statischer Guss gewählt werden. Die Aceros-Technik bewertet das geeignete Verfahren.</p>` },
    'bucha-bimetalica-sink-roll': { titulo: 'Sink-Roll-Buchsen: Kriterien für Spezifikation und Fertigung', descricao: 'Erforderliche Angaben für eine Endbuchse einer Sink Roll in einer Verzinkungslinie.', conteudo: `<p>Die <strong>Endbuchse der Sink Roll</strong> gehört zu einer Baugruppe im Feuerverzinkungsbad. Werkstoff, Maße, Oberfläche und Toleranzen müssen Zeichnung und Betriebsbedingungen entsprechen.</p><h2>Erforderliche Angaben</h2><ul><li>Zeichnungen und Maße von Zapfen, Buchse und zugehörigen Teilen.</li><li>Bad, Temperatur, Lasten und Verschleißhistorie.</li><li>Bisheriger Werkstoff sowie Ausfall- und Wartungsdaten.</li></ul><h2>Fertigung bei Aceros</h2><p>Aceros fertigt Buchsen im Schleuderguss und bearbeitet sie nach Zeichnung. Je nach Projekt sind chemische Analyse, Härteprüfung, Ultraschall und Maßprüfung vorgesehen.</p>` },
    'ligas-304-316-310-alta-temperatura': { titulo: 'Edelstähle 304, 316 und 310 bei hohen Temperaturen', descricao: 'Vergleich von Zusammensetzung, Korrosionsbeständigkeit und typischen Anwendungen.', conteudo: `<p><strong>304, 316 und 310</strong> sind austenitische Edelstähle mit unterschiedlicher Legierungszusammensetzung und Verwendung.</p><h2>Sorten im Vergleich</h2><p>304 ist ein vielseitiger Edelstahl. 316 enthält Molybdän und bietet in vielen chloridhaltigen Umgebungen erhöhte Beständigkeit. 310 hat höhere Chrom- und Nickelgehalte und wird häufig wegen seiner Oxidationsbeständigkeit bei hohen Temperaturen berücksichtigt.</p><h2>Auswahl für die Anwendung</h2><p>Temperatur allein genügt nicht: Atmosphäre, Lasten, Korrosion, Zyklen und die geltende Norm zählen ebenfalls. Bei anspruchsvollerem Betrieb kann eine ASTM-A297-Gusssorte geprüft werden. Richttemperaturen ersetzen keine projektspezifische Auslegung.</p>` },
  },
  it: {
    'sink-roll-como-escolher-liga': { titulo: 'Sink Roll: scegliere la lega per le linee di zincatura', descricao: 'Valutare bagno, temperatura, geometria e storia operativa prima di specificare la lega.', conteudo: `<p>Il <strong>Sink Roll</strong> lavora immerso nel bagno di zinco di una linea di zincatura a caldo. La specifica deve considerare composizione e temperatura del bagno, geometria, carichi e storia operativa.</p><h2>Criteri di scelta</h2><ul><li>Composizione e temperatura del bagno.</li><li>Geometria, velocità della linea e progetto delle estremità.</li><li>Usura, manutenzione e guasti precedenti.</li></ul><p>Aceros fornisce Sink Rolls, boccole terminali, bracci, snout e gruppi assemblati su disegno del cliente. Il materiale viene scelto per l’applicazione reale.</p><h2>Produzione e controlli</h2><p>Il progetto può includere colata centrifuga, lavorazione, analisi chimica, durezza, ultrasuoni e controllo dimensionale secondo i requisiti di fornitura.</p>` },
    'astm-a297-hk-hh-hp-diferencas': { titulo: 'ASTM A297: differenze tra i gradi HH, HK e HP', descricao: 'Panoramica degli acciai fusi resistenti al calore HH, HK e HP e delle applicazioni tipiche.', conteudo: `<p>La norma <strong>ASTM A297</strong> comprende acciai fusi resistenti al calore con diversi contenuti di cromo e nichel. HH, HK e HP vanno valutati in base a disegno, temperatura, atmosfera del forno e ciclo operativo.</p><h2>Applicazioni tipiche</h2><p>HH può essere valutato per componenti di forni di trattamento termico; HK per diversi componenti di forni industriali; HP è spesso specificato per tubi di reformer. La scelta dipende da tutte le condizioni di servizio.</p><h2>Specifica tecnica</h2><p>Aceros verifica temperatura, atmosfera, cicli termici e storia applicativa. I valori indicativi non sostituiscono l’edizione applicabile della norma né la specifica finale del progetto.</p>` },
    'fundicao-centrifugada-vantagens': { titulo: 'Colata centrifuga: vantaggi e quando utilizzarla', descricao: 'Come la colata centrifuga forma pezzi tubolari e quando è indicata la colata statica.', conteudo: `<p>Nella <strong>colata centrifuga</strong>, l’acciaio liquido viene versato in uno stampo preriscaldato e in rotazione. La forza centrifuga spinge il metallo verso la parete formando un pezzo tubolare.</p><h2>Vantaggi per i componenti tubolari</h2><p>Il processo favorisce pareti dense e diametri interno ed esterno concentrici. La lavorazione successiva consente di raggiungere quote e tolleranze del disegno. Velocità, diametro dello stampo e massa sono definiti per ogni progetto.</p><h2>Quando scegliere la colata statica</h2><p>La colata statica può essere adatta a geometrie non centrifugabili, come carter complessi e parti asimmetriche. L’ingegneria Aceros valuta il processo più idoneo.</p>` },
    'bucha-bimetalica-sink-roll': { titulo: 'Boccole per Sink Roll: criteri di specifica e produzione', descricao: 'Dati necessari per specificare una boccola terminale per Sink Roll in una linea di zincatura.', conteudo: `<p>La <strong>boccola terminale del Sink Roll</strong> fa parte di un gruppo che lavora nel bagno di zincatura a caldo. Materiale, dimensioni, finitura e tolleranze devono seguire il disegno e le condizioni di servizio.</p><h2>Dati da valutare</h2><ul><li>Disegni e dimensioni dell’estremità, della boccola e delle parti collegate.</li><li>Bagno, temperatura, carichi e storia dell’usura.</li><li>Materiale in uso e registri di guasti o manutenzione.</li></ul><h2>Produzione Aceros</h2><p>Aceros produce boccole mediante colata centrifuga e le lavora su disegno. Il controllo può includere analisi chimica, durezza, ultrasuoni e verifica dimensionale.</p>` },
    'ligas-304-316-310-alta-temperatura': { titulo: 'Acciai inox 304, 316 e 310 alle alte temperature', descricao: 'Confronto tra composizione, resistenza alla corrosione e applicazioni tipiche.', conteudo: `<p><strong>304, 316 e 310</strong> sono acciai inox austenitici con composizioni e impieghi differenti.</p><h2>Confronto tra i gradi</h2><p>304 è un inox di uso generale. 316 contiene molibdeno e migliora la resistenza in molti ambienti con cloruri. 310 ha più cromo e nichel ed è spesso valutato per la resistenza all’ossidazione ad alte temperature.</p><h2>Scelta per l’applicazione</h2><p>La sola temperatura non basta: contano anche atmosfera, carichi, corrosione, cicli e norma applicabile. In servizio più gravoso si può valutare un grado fuso ASTM A297. Le temperature indicative non sostituiscono l’analisi del progetto.</p>` },
  },
};

export const blogUi: Record<Language, { eyebrow: string; heading: string; lead: string; featured: string; more: string; read: string; contactTitle: string; contactLead: string; contactButton: string; back: string; reading: string; applyTitle: string; applyLead: string; continue: string; categories: Record<BlogPost['categoria'], string>; solutions: string[] }> = {
  pt: { eyebrow: 'Conteúdo Técnico', heading: 'Engenharia em Aços Centrifugados', lead: 'Guias técnicos para engenheiros de projeto, compras e manutenção industrial. Ligas, processos, aplicações e controle de qualidade na fabricação industrial.', featured: 'Em destaque', more: 'Mais artigos técnicos', read: 'Ler artigo completo', contactTitle: 'Precisa de assessoria técnica no seu projeto?', contactLead: 'Nossa equipe técnica avalia o desenho e os requisitos da aplicação para orientar os próximos passos e preparar o orçamento.', contactButton: 'Falar com a equipe técnica', back: 'Voltar para o blog', reading: 'de leitura', applyTitle: 'Precisa aplicar esse conhecimento no seu projeto?', applyLead: 'Nossa equipe técnica avalia o desenho e os requisitos da aplicação para orientar os próximos passos do projeto.', continue: 'Continue lendo', categories: { Processo: 'Processo', Ligas: 'Ligas', Aplicações: 'Aplicações', Engenharia: 'Engenharia' }, solutions: ['Conhecer Sink Rolls e componentes', 'Conhecer os rolos de forno', 'Conhecer a fundição centrifugada', 'Conhecer as buchas para Sink Roll', 'Conhecer os tubos centrifugados'] },
  en: { eyebrow: 'Technical content', heading: 'Centrifugal steel engineering', lead: 'Technical guides for design, purchasing and maintenance engineers. Alloys, processes, applications and quality control in industrial manufacturing.', featured: 'Featured', more: 'More technical articles', read: 'Read full article', contactTitle: 'Need technical guidance for your project?', contactLead: 'Our team reviews your drawing and application requirements to define the next steps and prepare a quotation.', contactButton: 'Contact our technical team', back: 'Back to the blog', reading: 'read', applyTitle: 'Applying this knowledge to a project?', applyLead: 'Our technical team reviews the drawing and application requirements to guide the next steps.', continue: 'Keep reading', categories: { Processo: 'Process', Ligas: 'Alloys', Aplicações: 'Applications', Engenharia: 'Engineering' }, solutions: ['Explore Sink Rolls and components', 'Explore furnace rolls', 'Explore centrifugal casting', 'Explore Sink Roll bushings', 'Explore centrifugally cast tubes'] },
  es: { eyebrow: 'Contenido técnico', heading: 'Ingeniería en aceros centrifugados', lead: 'Guías técnicas para ingenieros de diseño, compras y mantenimiento. Aleaciones, procesos, aplicaciones y control de calidad en la fabricación industrial.', featured: 'Destacado', more: 'Más artículos técnicos', read: 'Leer artículo completo', contactTitle: '¿Necesita asesoría técnica para su proyecto?', contactLead: 'Nuestro equipo revisa el plano y los requisitos de la aplicación para definir los próximos pasos y preparar una cotización.', contactButton: 'Hablar con el equipo técnico', back: 'Volver al blog', reading: 'de lectura', applyTitle: '¿Quiere aplicar estos conocimientos a su proyecto?', applyLead: 'Nuestro equipo técnico revisa el plano y los requisitos de la aplicación para orientar los próximos pasos.', continue: 'Seguir leyendo', categories: { Processo: 'Proceso', Ligas: 'Aleaciones', Aplicações: 'Aplicaciones', Engenharia: 'Ingeniería' }, solutions: ['Conocer Sink Rolls y componentes', 'Conocer los rodillos de horno', 'Conocer la fundición centrífuga', 'Conocer los bujes para Sink Roll', 'Conocer los tubos centrifugados'] },
  de: { eyebrow: 'Fachwissen', heading: 'Technik für Schleuderguss-Stahl', lead: 'Fachartikel für Konstruktion, Einkauf und Instandhaltung. Legierungen, Verfahren, Anwendungen und Qualitätskontrolle in der industriellen Fertigung.', featured: 'Im Fokus', more: 'Weitere Fachartikel', read: 'Ganzen Artikel lesen', contactTitle: 'Benötigen Sie technische Beratung für Ihr Projekt?', contactLead: 'Unser Team prüft Zeichnung und Anwendungsanforderungen, um die nächsten Schritte und ein Angebot vorzubereiten.', contactButton: 'Technikteam kontaktieren', back: 'Zurück zum Blog', reading: 'Lesezeit', applyTitle: 'Dieses Wissen im Projekt anwenden?', applyLead: 'Unser Technikteam prüft Zeichnung und Anforderungen und berät zu den nächsten Schritten.', continue: 'Weiterlesen', categories: { Processo: 'Verfahren', Ligas: 'Legierungen', Aplicações: 'Anwendungen', Engenharia: 'Technik' }, solutions: ['Sink Rolls und Bauteile ansehen', 'Ofenrollen ansehen', 'Schleuderguss ansehen', 'Sink-Roll-Buchsen ansehen', 'Schleudergussrohre ansehen'] },
  it: { eyebrow: 'Contenuti tecnici', heading: 'Ingegneria degli acciai centrifugati', lead: 'Guide tecniche per progettazione, acquisti e manutenzione. Leghe, processi, applicazioni e controllo qualità nella produzione industriale.', featured: 'In evidenza', more: 'Altri articoli tecnici', read: 'Leggi l’articolo completo', contactTitle: 'Serve una consulenza tecnica per il progetto?', contactLead: 'Il nostro team esamina il disegno e i requisiti applicativi per definire i prossimi passi e preparare un preventivo.', contactButton: 'Contatta il team tecnico', back: 'Torna al blog', reading: 'di lettura', applyTitle: 'Vuoi applicare queste informazioni al tuo progetto?', applyLead: 'Il nostro team tecnico esamina il disegno e i requisiti per orientare i prossimi passi.', continue: 'Continua a leggere', categories: { Processo: 'Processo', Ligas: 'Leghe', Aplicações: 'Applicazioni', Engenharia: 'Ingegneria' }, solutions: ['Scopri Sink Rolls e componenti', 'Scopri i rulli per forni', 'Scopri la colata centrifuga', 'Scopri le boccole per Sink Roll', 'Scopri i tubi centrifugati'] },
};

export function getBlogPosts(language: Language): BlogPost[] {
  if (language === 'pt') return blogPosts;
  return blogPosts.map(post => ({ ...post, ...articles[language][post.slug] }));
}

export function formatLocalizedBlogDate(date: string, language: Language) {
  const locale = { pt: 'pt-BR', en: 'en-US', es: 'es-ES', de: 'de-DE', it: 'it-IT' }[language];
  return new Intl.DateTimeFormat(locale, { timeZone: 'UTC', year: 'numeric', month: 'long', day: 'numeric' }).format(new Date(`${date}T00:00:00Z`));
}
