import type { Language } from '@/hooks/use-language';

// Captions follow the gallery order: product-gallery-1..11, then history-1,2,4..10.
export const galleryCaptions: Record<Language, string[]> = {
  pt: [
    'Componente rotativo industrial em inspeção e acabamento', 'Conjunto de componentes tubulares para aplicação industrial', 'Conjunto de rolos industriais fabricados sob medida', 'Rolos industriais preparados para montagem', 'Grelha metálica fundida para operação industrial', 'Rotor industrial em processo de usinagem', 'Componentes industriais fabricados e organizados para expedição', 'Peças usinadas com detalhes de acabamento e inspeção', 'Rolos e componentes cilíndricos usinados', 'Análise química por espectrometria no controle do material', 'Conjunto de rolo industrial montado para inspeção',
    'Rolos, conjuntos radiantes e serpentinas para aplicações térmicas e siderúrgicas', 'Inspeção de perfil com equipamento Rollprof em rolos industriais', 'Rolos, conjuntos radiantes e processos de soldagem aplicados à fabricação', 'Vigas transportadoras e rolos para lingotamento contínuo', 'Rolos e componentes cilíndricos em diferentes etapas de fabricação', 'Rolos industriais preparados para aplicações em fornos', 'Sink rolls, braços e componentes para linhas de galvanização', 'Processo de centrifugação de tubos em liga ASTM A297', 'Tubo centrifugado em etapas de fusão, usinagem e polimento',
  ],
  en: [
    'Industrial rotating component during inspection and finishing', 'Tubular components for industrial applications', 'Custom manufactured industrial rolls', 'Industrial rolls ready for assembly', 'Cast metal grate for industrial use', 'Industrial rotor during machining', 'Industrial components ready for dispatch', 'Machined parts showing finishing and inspection details', 'Machined rolls and cylindrical components', 'Chemical analysis by spectrometry for material control', 'Industrial roll assembly prepared for inspection',
    'Rolls, radiant assemblies and coils for thermal and steel applications', 'Roll profile inspection with Rollprof equipment', 'Rolls, radiant assemblies and welding processes in manufacturing', 'Transport beams and rolls for continuous casting', 'Rolls and cylindrical components at different manufacturing stages', 'Industrial rolls prepared for furnace applications', 'Sink rolls, arms and components for galvanizing lines', 'Centrifugal casting of ASTM A297 alloy tubes', 'Centrifugally cast tube during melting, machining and polishing',
  ],
  es: [
    'Componente rotativo industrial durante inspección y acabado', 'Componentes tubulares para aplicaciones industriales', 'Rodillos industriales fabricados a medida', 'Rodillos industriales listos para montaje', 'Rejilla metálica fundida para uso industrial', 'Rotor industrial durante el mecanizado', 'Componentes industriales preparados para expedición', 'Piezas mecanizadas con detalles de acabado e inspección', 'Rodillos y componentes cilíndricos mecanizados', 'Análisis químico por espectrometría para control del material', 'Conjunto de rodillo industrial preparado para inspección',
    'Rodillos, conjuntos radiantes y serpentines para aplicaciones térmicas y siderúrgicas', 'Inspección del perfil de rodillos con equipo Rollprof', 'Rodillos, conjuntos radiantes y procesos de soldadura en fabricación', 'Vigas transportadoras y rodillos para colada continua', 'Rodillos y componentes cilíndricos en distintas etapas de fabricación', 'Rodillos industriales para aplicaciones en hornos', 'Sink rolls, brazos y componentes para líneas de galvanizado', 'Fundición centrífuga de tubos de aleación ASTM A297', 'Tubo centrifugado durante fusión, mecanizado y pulido',
  ],
  de: [
    'Rotierendes Industriebauteil bei Prüfung und Endbearbeitung', 'Rohrförmige Bauteile für Industrieanwendungen', 'Maßgefertigte Industrierollen', 'Industrierollen zur Montage vorbereitet', 'Gegossener Metallrost für Industrieanlagen', 'Industrierotor während der Bearbeitung', 'Industriebauteile für den Versand vorbereitet', 'Bearbeitete Teile mit Details zu Endbearbeitung und Prüfung', 'Bearbeitete Rollen und zylindrische Bauteile', 'Chemische Analyse mittels Spektrometrie zur Werkstoffkontrolle', 'Industrierollenbaugruppe zur Prüfung vorbereitet',
    'Rollen, Strahlungsbaugruppen und Rohrschlangen für Wärme- und Stahlanwendungen', 'Profilprüfung an Industrierollen mit Rollprof', 'Rollen, Strahlungsbaugruppen und Schweißverfahren in der Fertigung', 'Transportbalken und Rollen für Strangguss', 'Rollen und zylindrische Bauteile in verschiedenen Fertigungsphasen', 'Industrierollen für Ofenanwendungen', 'Sink Rolls, Arme und Bauteile für Verzinkungslinien', 'Schleuderguss von Rohren aus ASTM-A297-Legierung', 'Schleudergegossenes Rohr beim Schmelzen, Bearbeiten und Polieren',
  ],
  it: [
    'Componente rotante industriale durante ispezione e finitura', 'Componenti tubolari per applicazioni industriali', 'Rulli industriali prodotti su misura', 'Rulli industriali pronti per il montaggio', 'Griglia metallica fusa per uso industriale', 'Rotore industriale durante la lavorazione', 'Componenti industriali preparati per la spedizione', 'Parti lavorate con dettagli di finitura e ispezione', 'Rulli e componenti cilindrici lavorati', 'Analisi chimica mediante spettrometria per il controllo del materiale', 'Gruppo di rullo industriale preparato per l’ispezione',
    'Rulli, gruppi radianti e serpentine per applicazioni termiche e siderurgiche', 'Ispezione del profilo dei rulli con apparecchiatura Rollprof', 'Rulli, gruppi radianti e processi di saldatura nella produzione', 'Travi di trasporto e rulli per colata continua', 'Rulli e componenti cilindrici nelle varie fasi produttive', 'Rulli industriali per applicazioni nei forni', 'Sink rolls, bracci e componenti per linee di zincatura', 'Colata centrifuga di tubi in lega ASTM A297', 'Tubo centrifugato durante fusione, lavorazione e lucidatura',
  ],
};
