import type { Language } from '@/hooks/use-language';

export type BuchaCopy = {
  heroEyebrow: string; heroTitle: string; heroLead: string;
  ctaRequestQuote: string; ctaWhatsappTeam: string;
  strip: [string, string, string, string, string];
  introTitle: string; introP1a: string; introP1b: string; introP2a: string; introP2b: string;
  specsTitle: string; specsCol1: string; specsCol2: string;
  specRows: Array<[string, string]>;
  specsFooter: string;
  differentialsTitle: string; differentialsLead: string;
  differentials: Array<{ title: string; text: string }>;
  applicationsTitle: string; applicationsLead: string;
  applicationLabels: string[];
  applicationsFooter: string;
  galleryTitle: string;
  galleryAlts: string[];
  processTitle: string;
  processSteps: Array<{ title: string; desc: string }>;
  whyTitle: string;
  whyPoints: string[];
  isoBadge: string; isoTitle1: string; isoTitleAccent: string; isoLead: string;
  isoCertLabel: string; isoValidLabel: string;
  isoFooter: string;
  ctaMidTitle: string; ctaMidLead: string;
  ctaMidRequest: string; ctaMidWhatsapp: string;
  faqTitle: string;
  faqs: Array<{ q: string; a: string }>;
  formTitle: string; formLead1: string; formLead2: string;
  formName: string; formNamePh: string; formCompany: string; formCompanyPh: string;
  formPhone: string; formCity: string; formCityPh: string;
  formEmail: string; formEmailPh: string;
  formMaterial: string; formMaterialPh: string;
  formDeadline: string; formDeadlinePh: string;
  formDimensions: string; formDimensionsPh: string;
  formDrawing: string; formDrawingHelp: string;
  formMessage: string; formMessagePh: string;
  formPrivacyA: string; formPrivacyLink: string; formPrivacyB: string;
  formSubmitting: string; formSubmit: string;
  toastOkTitle: string; toastOkDesc: string;
  toastErrTitle: string; toastErrDesc: string;
  zoomAria: string;
  whatsappMessage: string;
};

export const buchaCopy: Record<Language, BuchaCopy> = {
  pt: {
    heroEyebrow: 'Fabricação industrial sob medida',
    heroTitle: 'Bucha de Aço Inox Fabricada Sob Medida',
    heroLead: 'Buchas centrifugadas e usinadas conforme desenho técnico, com liga selecionada para a condição de serviço.',
    ctaRequestQuote: 'Solicitar Orçamento', ctaWhatsappTeam: 'Falar com a equipe técnica',
    strip: ['Fabricação sob medida', 'Conforme desenho técnico', 'Atendimento Brasil e exterior', 'Controle de qualidade', 'Equipe especializada'],
    introTitle: 'Excelência em Componentes Industriais',
    introP1a: 'A Aceros é a divisão de aços inoxidáveis do grupo ', introP1b: 'Metalúrgica Daniela. Não comercializamos produtos commodities ou tubos comuns de prateleira: nossa fábrica produz via processo de centrifugação peças de alta liga resistentes a calor, abrasão e oxidação severa (norma ASTM A297), usinadas sob medida para o projeto do cliente.',
    introP2a: 'Nossa engenharia fornece ', introP2b: 'buchas para ponta de Sink Roll (rolos para potes de zinco em linhas de galvanização) e componentes para Rolos de Forno (Furnace Rolls para tratamento térmico), usinados conforme o desenho e as condições de trabalho informadas pelo cliente.',
    specsTitle: 'Especificações Técnicas', specsCol1: 'Categoria', specsCol2: 'Detalhes Disponíveis',
    specRows: [
      ['Ligas Disponíveis', 'Ligas selecionadas conforme a aplicação, incluindo materiais conforme ASTM A297 quando aplicável'],
      ['Processo Produtivo', 'Fundição por Centrifugação ou Estática + Usinagem CNC de Precisão'],
      ['Aplicações Especiais', 'Buchas para ponta de Sink Roll e Rolos de Forno (Furnace Roll)'],
      ['Dimensões', 'Diâmetros e comprimentos sob consulta (Fabricação conforme projeto)'],
      ['Normas Técnicas', 'ABNT, ASTM, DIN, AISI'],
      ['Inspeção', 'Rastreabilidade e ensaios definidos para o fornecimento, incluindo dureza, análise química, ultrassom e líquido penetrante quando aplicáveis'],
    ],
    specsFooter: 'Consulte nossa equipe técnica para especificações conforme sua necessidade.',
    differentialsTitle: 'Diferenciais Aceros',
    differentialsLead: 'Capacidades técnicas para a fabricação de buchas centrifugadas sob medida.',
    differentials: [
      { title: 'Peça de Alta Liga (Não Commodity)', text: 'Fabricação própria por centrifugação + Engenharia de Materiais + Usinagem CNC sob medida.' },
      { title: 'Fabricação sob medida', text: 'Produção customizada para atender requisitos exatos de montagem.' },
      { title: 'Seleção de ligas', text: 'Material definido conforme abrasão, corrosão, temperatura e requisitos mecânicos.' },
      { title: 'Controle de qualidade', text: 'Inspeções e ensaios definidos conforme os requisitos do fornecimento.' },
      { title: 'Atendimento técnico', text: 'Apoio da equipe de engenharia na análise da aplicação.' },
      { title: 'Produção conforme projeto', text: 'Fabricação e usinagem orientadas pelo desenho técnico.' },
      { title: 'Soluções personalizadas', text: 'Desenvolvimento conforme as condições de serviço informadas pelo cliente.' },
      { title: 'Brasil e exterior', text: 'Atendimento comercial para projetos nacionais e internacionais.' },
      { title: 'Aplicações severas', text: 'Componentes desenvolvidos para condições térmicas, mecânicas e químicas específicas.' },
    ],
    applicationsTitle: 'Principais Aplicações',
    applicationsLead: 'Aplicações atendidas conforme desenho e requisitos de operação.',
    applicationLabels: ['Mineração', 'Siderurgia', 'Sink Roll & Pontas', 'Rolos de Forno', 'Tratamento Térmico', 'Galvanização', 'Metalurgia'],
    applicationsFooter: 'Cada projeto é analisado conforme aplicação, desenho técnico, material e requisitos de inspeção informados pelo cliente.',
    galleryTitle: 'Galeria de Produtos',
    galleryAlts: [
      'Bucha de aço inox usinada sob medida da Aceros',
      'Bucha centrifugada de aço inox para aplicação industrial',
      'Bucha de aço inox com acabamento e usinagem de alta precisão',
      'Bucha para ponta de sink roll, fabricação Aceros',
      'Bucha de aço inox em inspeção dimensional',
      'Bucha de aço inox pronta para expedição',
    ],
    processTitle: 'Nosso Processo',
    processSteps: [
      { title: 'Recebimento do Projeto', desc: 'Análise detalhada dos requisitos fornecidos.' },
      { title: 'Análise Técnica', desc: 'Validação de tolerâncias e viabilidade produtiva pela engenharia.' },
      { title: 'Definição da Liga', desc: 'Seleção do material conforme as condições de serviço e a norma aplicável.' },
      { title: 'Fabricação', desc: 'Geração do blank por centrifugação e usinagem CNC de precisão.' },
      { title: 'Controle Dimensional', desc: 'Medição das dimensões e tolerâncias especificadas no desenho.' },
      { title: 'Inspeção de Qualidade', desc: 'Ensaios e verificações definidos conforme os requisitos do fornecimento.' },
      { title: 'Entrega', desc: 'Expedição protegida conforme as condições definidas na proposta.' },
    ],
    whyTitle: 'Por que escolher a Aceros',
    whyPoints: [
      'Divisão de inoxidáveis do Grupo Metalúrgica Daniela',
      'Fabricação por centrifugação em ligas ASTM A297, quando aplicável',
      'Experiência em componentes para Sink Roll e Furnace Roll',
      'Desenvolvimento de componentes sob medida (não commodities)',
      'Controle e rastreabilidade conforme os requisitos do fornecimento',
      'Soluções para aplicações sujeitas a calor, abrasão e corrosão',
    ],
    isoBadge: 'Certificação Internacional',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'Certificada',
    isoLead: 'Nosso Sistema de Gestão da Qualidade é certificado pela DQS GmbH, com acreditação DAkkS e reconhecimento da rede IQNet.',
    isoCertLabel: 'Certificado', isoValidLabel: 'Válido até',
    isoFooter: 'Conforme os requisitos do fornecimento, a documentação pode incluir rastreabilidade, laudo metalúrgico, ensaios de dureza, análise química e ultrassom.',
    ctaMidTitle: 'Precisa de uma Bucha de Aço Inox?',
    ctaMidLead: 'Nossa equipe técnica avalia o desenho e as condições de serviço para orientar os próximos passos do projeto.',
    ctaMidRequest: 'Solicitar Cotação', ctaMidWhatsapp: 'Enviar Projeto via WhatsApp',
    faqTitle: 'Perguntas Frequentes',
    faqs: [
      { q: 'Quais as vantagens das buchas para Sink Roll da Aceros?', a: 'Fabricadas por centrifugação e usinadas conforme desenho, são destinadas às pontas de Sink Rolls e a outras aplicações industriais definidas conforme a condição de operação.' },
      { q: 'Vocês trabalham com produtos commodities / tubos de prateleira?', a: 'Não. A Aceros é focada exclusivamente em engenharia e fabricação sob medida de componentes de alta liga centrifugados e usinados conforme desenho técnico.' },
      { q: 'Qual a aplicação das buchas para Rolos de Forno (Furnace Rolls)?', a: 'São componentes dimensionados conforme o desenho e as condições de operação dos rolos utilizados em fornos de tratamento térmico.' },
      { q: 'Quais ligas de aço inox a Aceros utiliza na fabricação?', a: 'A liga é selecionada pela engenharia conforme a temperatura, corrosão, abrasão e requisitos dimensionais do projeto, incluindo materiais conforme ASTM A297 quando aplicável.' },
      { q: 'A Aceros produz buchas conforme desenho técnico?', a: 'Sim. A fabricação e a usinagem são realizadas sob medida conforme o desenho técnico e os requisitos informados pelo cliente.' },
    ],
    formTitle: 'Solicite seu Orçamento de Buchas',
    formLead1: 'Nossa equipe técnica analisa as informações do projeto e prepara a proposta comercial.',
    formLead2: 'Retorno comercial em até um dia útil.',
    formName: 'Nome Completo', formNamePh: 'Seu nome',
    formCompany: 'Empresa', formCompanyPh: 'Nome da empresa',
    formPhone: 'Telefone / WhatsApp',
    formCity: 'Cidade / UF', formCityPh: 'Cidade - UF',
    formEmail: 'E-mail Corporativo', formEmailPh: 'email@empresa.com.br',
    formMaterial: 'Liga ou material', formMaterialPh: 'Se conhecido',
    formDeadline: 'Prazo desejado', formDeadlinePh: 'Ex.: 60 dias',
    formDimensions: 'Dimensões e quantidade', formDimensionsPh: 'Diâmetros, comprimento e quantidade',
    formDrawing: 'Desenho técnico', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG ou PNG, até 5 MB.',
    formMessage: 'Informações adicionais', formMessagePh: 'Informe a aplicação, o conjunto e outras condições de operação.',
    formPrivacyA: 'Li e aceito a ', formPrivacyLink: 'Política de Privacidade', formPrivacyB: ' e autorizo o uso dos dados para retorno desta solicitação.',
    formSubmitting: 'Enviando...', formSubmit: 'Solicitar Orçamento',
    toastOkTitle: 'Solicitação Recebida!', toastOkDesc: 'Sua mensagem foi enviada com sucesso. Nossa equipe entrará em contato em breve.',
    toastErrTitle: 'Ops! Algo deu errado', toastErrDesc: 'Tente enviar novamente ou use o botão do WhatsApp para um atendimento imediato.',
    zoomAria: 'Ampliar',
    whatsappMessage: 'Olá! Gostaria de um orçamento para Buchas de Aço Inox sob medida.',
  },
  en: {
    heroEyebrow: 'Custom industrial manufacturing',
    heroTitle: 'Stainless Steel Bushings Made to Order',
    heroLead: 'Centrifugally cast bushings machined to your drawing, with the alloy selected for the service condition.',
    ctaRequestQuote: 'Request a quote', ctaWhatsappTeam: 'Talk to the technical team',
    strip: ['Custom manufacturing', 'Made to drawing', 'Serving Brazil and abroad', 'Quality control', 'Specialised team'],
    introTitle: 'Excellence in industrial components',
    introP1a: 'Aceros is the stainless-steel division of the ', introP1b: 'Metalúrgica Daniela group. We do not sell commodities or off-the-shelf tubes: our shop produces high-alloy centrifugally cast parts resistant to heat, abrasion and severe oxidation (ASTM A297), machined to the customer\'s drawing.',
    introP2a: 'Our engineering supplies ', introP2b: 'Sink-Roll end bushings (for zinc-pot rolls in galvanising lines) and components for Furnace Rolls (heat-treatment), machined to the drawing and operating conditions provided by the customer.',
    specsTitle: 'Technical specifications', specsCol1: 'Category', specsCol2: 'Available details',
    specRows: [
      ['Available alloys', 'Alloys selected per application, including materials to ASTM A297 where applicable'],
      ['Manufacturing process', 'Centrifugal or static casting + precision CNC machining'],
      ['Special applications', 'Sink-Roll end bushings and Furnace-Roll components'],
      ['Dimensions', 'Diameters and lengths on request (made to project)'],
      ['Technical standards', 'ABNT, ASTM, DIN, AISI'],
      ['Inspection', 'Traceability and tests defined for the supply, including hardness, chemical analysis, ultrasound and dye penetrant when applicable'],
    ],
    specsFooter: 'Consult our technical team for specifications matched to your needs.',
    differentialsTitle: 'Aceros differentials',
    differentialsLead: 'Technical capabilities for custom centrifugally cast bushings.',
    differentials: [
      { title: 'High-alloy part (not commodity)', text: 'In-house centrifugal casting + materials engineering + custom CNC machining.' },
      { title: 'Custom manufacturing', text: 'Production tailored to exact assembly requirements.' },
      { title: 'Alloy selection', text: 'Material defined per abrasion, corrosion, temperature and mechanical requirements.' },
      { title: 'Quality control', text: 'Inspections and tests defined per supply requirements.' },
      { title: 'Technical service', text: 'Engineering support in the application analysis.' },
      { title: 'Production to project', text: 'Manufacturing and machining driven by the technical drawing.' },
      { title: 'Bespoke solutions', text: 'Development to the service conditions provided by the customer.' },
      { title: 'Brazil and abroad', text: 'Commercial support for domestic and international projects.' },
      { title: 'Severe applications', text: 'Components engineered for specific thermal, mechanical and chemical conditions.' },
    ],
    applicationsTitle: 'Main applications',
    applicationsLead: 'Applications served according to drawing and operating requirements.',
    applicationLabels: ['Mining', 'Steelmaking', 'Sink Roll & ends', 'Furnace Rolls', 'Heat treatment', 'Galvanising', 'Metallurgy'],
    applicationsFooter: 'Every project is reviewed against application, technical drawing, material and inspection requirements provided by the customer.',
    galleryTitle: 'Product gallery',
    galleryAlts: [
      'Aceros custom-machined stainless steel bushing',
      'Centrifugally cast stainless steel bushing for industrial application',
      'Stainless steel bushing with precision finish and machining',
      'Sink-Roll end bushing manufactured by Aceros',
      'Stainless steel bushing under dimensional inspection',
      'Stainless steel bushing ready for shipping',
    ],
    processTitle: 'Our process',
    processSteps: [
      { title: 'Project intake', desc: 'Detailed review of the requirements provided.' },
      { title: 'Technical analysis', desc: 'Engineering validates tolerances and manufacturability.' },
      { title: 'Alloy definition', desc: 'Material selection per service conditions and applicable standard.' },
      { title: 'Manufacturing', desc: 'Blank produced by centrifugal casting followed by precision CNC machining.' },
      { title: 'Dimensional control', desc: 'Measurement of dimensions and tolerances defined on the drawing.' },
      { title: 'Quality inspection', desc: 'Tests and checks defined per supply requirements.' },
      { title: 'Delivery', desc: 'Protected shipment under the conditions defined in the proposal.' },
    ],
    whyTitle: 'Why choose Aceros',
    whyPoints: [
      'Stainless division of the Metalúrgica Daniela group',
      'Centrifugal casting in ASTM A297 alloys when applicable',
      'Experience with Sink-Roll and Furnace-Roll components',
      'Custom development (never commodities)',
      'Control and traceability per supply requirements',
      'Solutions for heat, abrasion and corrosion applications',
    ],
    isoBadge: 'International certification',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'Certified',
    isoLead: 'Our Quality Management System is certified by DQS GmbH, with DAkkS accreditation and IQNet network recognition.',
    isoCertLabel: 'Certificate', isoValidLabel: 'Valid through',
    isoFooter: 'According to supply requirements, documentation may include traceability, metallurgical report, hardness tests, chemical analysis and ultrasound.',
    ctaMidTitle: 'Need a stainless steel bushing?',
    ctaMidLead: 'Our technical team reviews the drawing and service conditions to advise the next steps of the project.',
    ctaMidRequest: 'Request a quote', ctaMidWhatsapp: 'Send the project on WhatsApp',
    faqTitle: 'Frequently asked questions',
    faqs: [
      { q: 'What are the advantages of Aceros sink-roll bushings?', a: 'Centrifugally cast and machined to drawing, intended for Sink-Roll ends and other industrial applications defined by the operating conditions.' },
      { q: 'Do you deal with commodities or off-the-shelf tubes?', a: 'No. Aceros focuses exclusively on custom engineering and manufacturing of high-alloy centrifugally cast and machined components to drawing.' },
      { q: 'What is the application of Furnace-Roll bushings?', a: 'They are components sized to the drawing and operating conditions of the rolls used in heat-treatment furnaces.' },
      { q: 'Which stainless steel alloys does Aceros use?', a: 'The alloy is selected by engineering based on temperature, corrosion, abrasion and dimensional requirements, including materials to ASTM A297 when applicable.' },
      { q: 'Does Aceros produce bushings from technical drawing?', a: 'Yes. Manufacturing and machining are done to the technical drawing and to the requirements provided by the customer.' },
    ],
    formTitle: 'Request your bushings quote',
    formLead1: 'Our technical team reviews the project information and prepares the commercial proposal.',
    formLead2: 'Commercial reply within one business day.',
    formName: 'Full name', formNamePh: 'Your name',
    formCompany: 'Company', formCompanyPh: 'Company name',
    formPhone: 'Phone / WhatsApp',
    formCity: 'City / State', formCityPh: 'City - State',
    formEmail: 'Business e-mail', formEmailPh: 'email@company.com',
    formMaterial: 'Alloy or material', formMaterialPh: 'If known',
    formDeadline: 'Desired lead time', formDeadlinePh: 'E.g. 60 days',
    formDimensions: 'Dimensions and quantity', formDimensionsPh: 'Diameters, length and quantity',
    formDrawing: 'Technical drawing', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG or PNG, up to 5 MB.',
    formMessage: 'Additional information', formMessagePh: 'Describe the application, the assembly and other operating conditions.',
    formPrivacyA: 'I have read and accept the ', formPrivacyLink: 'Privacy Policy', formPrivacyB: ' and authorise the use of my data to reply to this request.',
    formSubmitting: 'Sending...', formSubmit: 'Request a quote',
    toastOkTitle: 'Request received!', toastOkDesc: 'Your message has been sent. Our team will get in touch shortly.',
    toastErrTitle: 'Something went wrong', toastErrDesc: 'Please try again or use the WhatsApp button for immediate service.',
    zoomAria: 'Enlarge',
    whatsappMessage: 'Hi! I would like a quote for custom stainless steel bushings.',
  },
  es: {
    heroEyebrow: 'Fabricación industrial a medida',
    heroTitle: 'Buje de Acero Inoxidable Fabricado a Medida',
    heroLead: 'Bujes centrifugados y mecanizados según plano técnico, con la aleación seleccionada para la condición de servicio.',
    ctaRequestQuote: 'Solicitar presupuesto', ctaWhatsappTeam: 'Hablar con el equipo técnico',
    strip: ['Fabricación a medida', 'Según plano técnico', 'Atención Brasil y exterior', 'Control de calidad', 'Equipo especializado'],
    introTitle: 'Excelencia en componentes industriales',
    introP1a: 'Aceros es la división de aceros inoxidables del grupo ', introP1b: 'Metalúrgica Daniela. No comercializamos commodities ni tubos comunes de estantería: nuestra fábrica produce mediante centrifugación piezas de alta aleación resistentes a calor, abrasión y oxidación severa (norma ASTM A297), mecanizadas a medida para el proyecto del cliente.',
    introP2a: 'Nuestra ingeniería suministra ', introP2b: 'bujes para punta de Sink Roll (rodillos en potes de zinc en líneas de galvanizado) y componentes para Rodillos de Horno (Furnace Rolls, tratamiento térmico), mecanizados según el plano y las condiciones de operación indicadas por el cliente.',
    specsTitle: 'Especificaciones técnicas', specsCol1: 'Categoría', specsCol2: 'Detalles disponibles',
    specRows: [
      ['Aleaciones disponibles', 'Aleaciones seleccionadas según la aplicación, incluidos materiales según ASTM A297 cuando corresponda'],
      ['Proceso productivo', 'Fundición centrifugada o estática + mecanizado CNC de precisión'],
      ['Aplicaciones especiales', 'Bujes de punta de Sink Roll y componentes de Furnace Roll'],
      ['Dimensiones', 'Diámetros y longitudes bajo consulta (fabricación según proyecto)'],
      ['Normas técnicas', 'ABNT, ASTM, DIN, AISI'],
      ['Inspección', 'Trazabilidad y ensayos definidos para el suministro, incluidos dureza, análisis químico, ultrasonido y líquidos penetrantes cuando aplique'],
    ],
    specsFooter: 'Consulte a nuestro equipo técnico para especificaciones según su necesidad.',
    differentialsTitle: 'Diferenciales Aceros',
    differentialsLead: 'Capacidades técnicas para la fabricación de bujes centrifugados a medida.',
    differentials: [
      { title: 'Pieza de alta aleación (no commodity)', text: 'Fabricación propia por centrifugación + ingeniería de materiales + mecanizado CNC a medida.' },
      { title: 'Fabricación a medida', text: 'Producción personalizada para cumplir los requisitos exactos de montaje.' },
      { title: 'Selección de aleaciones', text: 'Material definido según abrasión, corrosión, temperatura y requisitos mecánicos.' },
      { title: 'Control de calidad', text: 'Inspecciones y ensayos definidos según los requisitos del suministro.' },
      { title: 'Atención técnica', text: 'Apoyo del equipo de ingeniería en el análisis de la aplicación.' },
      { title: 'Producción según proyecto', text: 'Fabricación y mecanizado orientados por el plano técnico.' },
      { title: 'Soluciones personalizadas', text: 'Desarrollo según las condiciones de servicio indicadas por el cliente.' },
      { title: 'Brasil y exterior', text: 'Atención comercial para proyectos nacionales e internacionales.' },
      { title: 'Aplicaciones severas', text: 'Componentes desarrollados para condiciones térmicas, mecánicas y químicas específicas.' },
    ],
    applicationsTitle: 'Principales aplicaciones',
    applicationsLead: 'Aplicaciones atendidas según plano y requisitos de operación.',
    applicationLabels: ['Minería', 'Siderurgia', 'Sink Roll & puntas', 'Rodillos de horno', 'Tratamiento térmico', 'Galvanizado', 'Metalurgia'],
    applicationsFooter: 'Cada proyecto se analiza según aplicación, plano técnico, material y requisitos de inspección indicados por el cliente.',
    galleryTitle: 'Galería de productos',
    galleryAlts: [
      'Buje de acero inoxidable mecanizado a medida por Aceros',
      'Buje centrifugado de acero inoxidable para aplicación industrial',
      'Buje de acero inoxidable con acabado y mecanizado de alta precisión',
      'Buje para punta de sink roll fabricado por Aceros',
      'Buje de acero inoxidable en inspección dimensional',
      'Buje de acero inoxidable listo para expedición',
    ],
    processTitle: 'Nuestro proceso',
    processSteps: [
      { title: 'Recepción del proyecto', desc: 'Análisis detallado de los requisitos aportados.' },
      { title: 'Análisis técnico', desc: 'Validación de tolerancias y viabilidad productiva por ingeniería.' },
      { title: 'Definición de la aleación', desc: 'Selección del material según las condiciones de servicio y la norma aplicable.' },
      { title: 'Fabricación', desc: 'Obtención del bruto por centrifugación y mecanizado CNC de precisión.' },
      { title: 'Control dimensional', desc: 'Medición de dimensiones y tolerancias especificadas en el plano.' },
      { title: 'Inspección de calidad', desc: 'Ensayos y verificaciones definidos según los requisitos del suministro.' },
      { title: 'Entrega', desc: 'Expedición protegida según las condiciones definidas en la propuesta.' },
    ],
    whyTitle: '¿Por qué elegir Aceros?',
    whyPoints: [
      'División de inoxidables del Grupo Metalúrgica Daniela',
      'Fabricación por centrifugación en aleaciones ASTM A297 cuando aplique',
      'Experiencia en componentes para Sink Roll y Furnace Roll',
      'Desarrollo de componentes a medida (no commodities)',
      'Control y trazabilidad según los requisitos del suministro',
      'Soluciones para aplicaciones con calor, abrasión y corrosión',
    ],
    isoBadge: 'Certificación internacional',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'Certificada',
    isoLead: 'Nuestro Sistema de Gestión de la Calidad está certificado por DQS GmbH, con acreditación DAkkS y reconocimiento de la red IQNet.',
    isoCertLabel: 'Certificado', isoValidLabel: 'Válido hasta',
    isoFooter: 'Según los requisitos del suministro, la documentación puede incluir trazabilidad, informe metalúrgico, ensayos de dureza, análisis químico y ultrasonido.',
    ctaMidTitle: '¿Necesita un buje de acero inoxidable?',
    ctaMidLead: 'Nuestro equipo técnico evalúa el plano y las condiciones de servicio para orientar los próximos pasos del proyecto.',
    ctaMidRequest: 'Solicitar cotización', ctaMidWhatsapp: 'Enviar proyecto por WhatsApp',
    faqTitle: 'Preguntas frecuentes',
    faqs: [
      { q: '¿Cuáles son las ventajas de los bujes de Sink Roll de Aceros?', a: 'Fabricados por centrifugación y mecanizados según plano, están destinados a las puntas de Sink Rolls y a otras aplicaciones industriales definidas por la condición de operación.' },
      { q: '¿Trabajan con commodities o tubos de estantería?', a: 'No. Aceros se enfoca exclusivamente en ingeniería y fabricación a medida de componentes de alta aleación centrifugados y mecanizados según plano técnico.' },
      { q: '¿Cuál es la aplicación de los bujes para Rodillos de Horno (Furnace Rolls)?', a: 'Son componentes dimensionados según el plano y las condiciones de operación de los rodillos utilizados en hornos de tratamiento térmico.' },
      { q: '¿Qué aleaciones de acero inoxidable utiliza Aceros?', a: 'La aleación es seleccionada por ingeniería según temperatura, corrosión, abrasión y requisitos dimensionales del proyecto, incluidos materiales según ASTM A297 cuando corresponda.' },
      { q: '¿Aceros produce bujes según plano técnico?', a: 'Sí. La fabricación y el mecanizado se realizan a medida según el plano técnico y los requisitos indicados por el cliente.' },
    ],
    formTitle: 'Solicite su cotización de bujes',
    formLead1: 'Nuestro equipo técnico analiza la información del proyecto y prepara la propuesta comercial.',
    formLead2: 'Respuesta comercial en un día hábil.',
    formName: 'Nombre completo', formNamePh: 'Su nombre',
    formCompany: 'Empresa', formCompanyPh: 'Nombre de la empresa',
    formPhone: 'Teléfono / WhatsApp',
    formCity: 'Ciudad / Estado', formCityPh: 'Ciudad - Estado',
    formEmail: 'E-mail corporativo', formEmailPh: 'email@empresa.com',
    formMaterial: 'Aleación o material', formMaterialPh: 'Si se conoce',
    formDeadline: 'Plazo deseado', formDeadlinePh: 'Ej.: 60 días',
    formDimensions: 'Dimensiones y cantidad', formDimensionsPh: 'Diámetros, longitud y cantidad',
    formDrawing: 'Plano técnico', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG o PNG, hasta 5 MB.',
    formMessage: 'Información adicional', formMessagePh: 'Indique la aplicación, el conjunto y otras condiciones de operación.',
    formPrivacyA: 'He leído y acepto la ', formPrivacyLink: 'Política de Privacidad', formPrivacyB: ' y autorizo el uso de los datos para responder a esta solicitud.',
    formSubmitting: 'Enviando...', formSubmit: 'Solicitar presupuesto',
    toastOkTitle: '¡Solicitud recibida!', toastOkDesc: 'Su mensaje fue enviado con éxito. Nuestro equipo se pondrá en contacto en breve.',
    toastErrTitle: '¡Ups! Algo salió mal', toastErrDesc: 'Intente enviar de nuevo o utilice el botón de WhatsApp para atención inmediata.',
    zoomAria: 'Ampliar',
    whatsappMessage: '¡Hola! Quisiera un presupuesto para Bujes de Acero Inoxidable a medida.',
  },
  de: {
    heroEyebrow: 'Kundenspezifische Industriefertigung',
    heroTitle: 'Edelstahlbuchse nach Maß gefertigt',
    heroLead: 'Schleudergegossene und nach Zeichnung bearbeitete Buchsen, mit Legierung passend zur Einsatzbedingung.',
    ctaRequestQuote: 'Angebot anfordern', ctaWhatsappTeam: 'Mit dem technischen Team sprechen',
    strip: ['Fertigung nach Maß', 'Nach technischer Zeichnung', 'Brasilien und international', 'Qualitätskontrolle', 'Spezialistenteam'],
    introTitle: 'Exzellenz in Industriekomponenten',
    introP1a: 'Aceros ist die Edelstahlsparte der Gruppe ', introP1b: 'Metalúrgica Daniela. Wir verkaufen keine Standardware oder Katalogrohre: Unser Werk fertigt im Schleuderguss hochlegierte Bauteile, beständig gegen Hitze, Verschleiß und starke Oxidation (ASTM A297), nach der Zeichnung des Kunden bearbeitet.',
    introP2a: 'Unsere Konstruktion liefert ', introP2b: 'Endbuchsen für Sink Rolls (Zinkbadrollen in Verzinkungslinien) und Komponenten für Furnace Rolls (Wärmebehandlung), bearbeitet nach Zeichnung und den vom Kunden vorgegebenen Betriebsbedingungen.',
    specsTitle: 'Technische Spezifikationen', specsCol1: 'Kategorie', specsCol2: 'Verfügbare Details',
    specRows: [
      ['Verfügbare Legierungen', 'Legierungen ausgewählt nach Anwendung, einschließlich Werkstoffen nach ASTM A297, wo zutreffend'],
      ['Fertigungsprozess', 'Schleuderguss oder statischer Guss + CNC-Präzisionsbearbeitung'],
      ['Spezialanwendungen', 'Endbuchsen für Sink Rolls und Furnace-Roll-Komponenten'],
      ['Abmessungen', 'Durchmesser und Längen auf Anfrage (Fertigung nach Projekt)'],
      ['Technische Normen', 'ABNT, ASTM, DIN, AISI'],
      ['Prüfung', 'Rückverfolgbarkeit und Prüfungen nach Lieferumfang, u. a. Härte, chemische Analyse, Ultraschall und Farbeindringprüfung wo anwendbar'],
    ],
    specsFooter: 'Für Spezifikationen nach Ihrem Bedarf sprechen Sie mit unserem Technik-Team.',
    differentialsTitle: 'Aceros-Alleinstellungsmerkmale',
    differentialsLead: 'Technische Kompetenzen für die Fertigung schleudergegossener Buchsen nach Maß.',
    differentials: [
      { title: 'Hochlegiertes Bauteil (keine Standardware)', text: 'Eigener Schleuderguss + Werkstofftechnik + CNC-Bearbeitung nach Maß.' },
      { title: 'Fertigung nach Maß', text: 'Herstellung auf exakte Montageanforderungen ausgerichtet.' },
      { title: 'Legierungswahl', text: 'Werkstoff festgelegt nach Verschleiß, Korrosion, Temperatur und mechanischen Anforderungen.' },
      { title: 'Qualitätskontrolle', text: 'Prüfungen und Kontrollen nach Liefervorgaben.' },
      { title: 'Technische Betreuung', text: 'Konstruktions-Support bei der Analyse der Anwendung.' },
      { title: 'Fertigung nach Projekt', text: 'Fertigung und Bearbeitung geführt durch die technische Zeichnung.' },
      { title: 'Individuelle Lösungen', text: 'Entwicklung nach den vom Kunden angegebenen Einsatzbedingungen.' },
      { title: 'Brasilien und Ausland', text: 'Kommerzielle Betreuung für nationale und internationale Projekte.' },
      { title: 'Schwere Einsätze', text: 'Bauteile ausgelegt für spezifische thermische, mechanische und chemische Bedingungen.' },
    ],
    applicationsTitle: 'Hauptanwendungen',
    applicationsLead: 'Anwendungen bedient nach Zeichnung und Betriebsanforderungen.',
    applicationLabels: ['Bergbau', 'Stahl', 'Sink Roll & Enden', 'Ofenrollen', 'Wärmebehandlung', 'Verzinkung', 'Metallurgie'],
    applicationsFooter: 'Jedes Projekt wird nach Anwendung, technischer Zeichnung, Werkstoff und Prüfvorgaben des Kunden bewertet.',
    galleryTitle: 'Produktgalerie',
    galleryAlts: [
      'Nach Maß bearbeitete Edelstahlbuchse von Aceros',
      'Schleudergegossene Edelstahlbuchse für industriellen Einsatz',
      'Edelstahlbuchse mit Präzisionsfinish und -bearbeitung',
      'Sink-Roll-Endbuchse von Aceros',
      'Edelstahlbuchse in der Maßprüfung',
      'Edelstahlbuchse versandbereit',
    ],
    processTitle: 'Unser Prozess',
    processSteps: [
      { title: 'Projektannahme', desc: 'Detaillierte Prüfung der übermittelten Anforderungen.' },
      { title: 'Technische Analyse', desc: 'Konstruktion prüft Toleranzen und Fertigbarkeit.' },
      { title: 'Legierungsdefinition', desc: 'Werkstoffwahl nach Einsatzbedingungen und geltender Norm.' },
      { title: 'Fertigung', desc: 'Rohteil im Schleuderguss und anschließende CNC-Präzisionsbearbeitung.' },
      { title: 'Maßkontrolle', desc: 'Messung der in der Zeichnung angegebenen Maße und Toleranzen.' },
      { title: 'Qualitätsprüfung', desc: 'Prüfungen und Kontrollen nach Liefervorgaben.' },
      { title: 'Lieferung', desc: 'Geschützter Versand nach den im Angebot festgelegten Bedingungen.' },
    ],
    whyTitle: 'Warum Aceros?',
    whyPoints: [
      'Edelstahlsparte der Metalúrgica Daniela Gruppe',
      'Fertigung im Schleuderguss in ASTM-A297-Legierungen, wo zutreffend',
      'Erfahrung mit Sink-Roll- und Furnace-Roll-Komponenten',
      'Entwicklung nach Maß (keine Standardware)',
      'Kontrolle und Rückverfolgbarkeit nach Lieferanforderungen',
      'Lösungen für Anwendungen mit Hitze, Verschleiß und Korrosion',
    ],
    isoBadge: 'Internationale Zertifizierung',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'zertifiziert',
    isoLead: 'Unser Qualitätsmanagementsystem ist von DQS GmbH zertifiziert, mit DAkkS-Akkreditierung und IQNet-Anerkennung.',
    isoCertLabel: 'Zertifikat', isoValidLabel: 'Gültig bis',
    isoFooter: 'Je nach Lieferanforderungen kann die Dokumentation Rückverfolgbarkeit, metallurgischen Bericht, Härteprüfung, chemische Analyse und Ultraschall enthalten.',
    ctaMidTitle: 'Brauchen Sie eine Edelstahlbuchse?',
    ctaMidLead: 'Unser Technik-Team prüft Zeichnung und Einsatzbedingungen und schlägt die nächsten Schritte des Projekts vor.',
    ctaMidRequest: 'Angebot anfordern', ctaMidWhatsapp: 'Projekt per WhatsApp senden',
    faqTitle: 'Häufige Fragen',
    faqs: [
      { q: 'Welche Vorteile bieten Sink-Roll-Buchsen von Aceros?', a: 'Im Schleuderguss gefertigt und nach Zeichnung bearbeitet, geeignet für Sink-Roll-Enden und weitere industrielle Anwendungen nach Betriebsbedingung.' },
      { q: 'Bieten Sie Standardware oder Katalogrohre an?', a: 'Nein. Aceros konzentriert sich ausschließlich auf Konstruktion und Fertigung hochlegierter Schleudergussbauteile nach Zeichnung.' },
      { q: 'Wofür werden Furnace-Roll-Buchsen eingesetzt?', a: 'Es handelt sich um Bauteile, die nach Zeichnung und Betriebsbedingungen von Ofenrollen in Wärmebehandlungsöfen ausgelegt sind.' },
      { q: 'Welche Edelstahllegierungen setzt Aceros ein?', a: 'Die Legierung wird von der Konstruktion nach Temperatur, Korrosion, Verschleiß und Maßanforderungen ausgewählt, u. a. Werkstoffe nach ASTM A297, wo zutreffend.' },
      { q: 'Fertigt Aceros Buchsen nach technischer Zeichnung?', a: 'Ja. Fertigung und Bearbeitung erfolgen nach der technischen Zeichnung und den vom Kunden angegebenen Anforderungen.' },
    ],
    formTitle: 'Angebot für Buchsen anfragen',
    formLead1: 'Unser Technik-Team prüft die Projektangaben und erstellt das Angebot.',
    formLead2: 'Kaufmännische Antwort innerhalb eines Werktags.',
    formName: 'Vollständiger Name', formNamePh: 'Ihr Name',
    formCompany: 'Unternehmen', formCompanyPh: 'Firmenname',
    formPhone: 'Telefon / WhatsApp',
    formCity: 'Ort / Land', formCityPh: 'Ort - Land',
    formEmail: 'Geschäftliche E-Mail', formEmailPh: 'email@firma.de',
    formMaterial: 'Legierung oder Werkstoff', formMaterialPh: 'Falls bekannt',
    formDeadline: 'Gewünschte Lieferzeit', formDeadlinePh: 'z. B. 60 Tage',
    formDimensions: 'Abmessungen und Menge', formDimensionsPh: 'Durchmesser, Länge und Menge',
    formDrawing: 'Technische Zeichnung', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG oder PNG, bis 5 MB.',
    formMessage: 'Weitere Angaben', formMessagePh: 'Bitte Anwendung, Baugruppe und weitere Betriebsbedingungen angeben.',
    formPrivacyA: 'Ich habe die ', formPrivacyLink: 'Datenschutzerklärung', formPrivacyB: ' gelesen und akzeptiert und stimme der Nutzung meiner Daten zur Beantwortung dieser Anfrage zu.',
    formSubmitting: 'Wird gesendet...', formSubmit: 'Angebot anfordern',
    toastOkTitle: 'Anfrage erhalten!', toastOkDesc: 'Ihre Nachricht wurde gesendet. Unser Team meldet sich in Kürze.',
    toastErrTitle: 'Etwas ist schiefgelaufen', toastErrDesc: 'Bitte erneut versuchen oder den WhatsApp-Button für sofortige Betreuung nutzen.',
    zoomAria: 'Vergrößern',
    whatsappMessage: 'Hallo! Ich möchte ein Angebot für Edelstahlbuchsen nach Maß anfragen.',
  },
  it: {
    heroEyebrow: 'Fabbricazione industriale su misura',
    heroTitle: 'Boccola in acciaio inossidabile realizzata su misura',
    heroLead: 'Boccole centrifugate e lavorate su disegno, con lega selezionata per la condizione di servizio.',
    ctaRequestQuote: 'Richiedi preventivo', ctaWhatsappTeam: 'Parla con il team tecnico',
    strip: ['Fabbricazione su misura', 'Su disegno tecnico', 'Servizio Brasile ed estero', 'Controllo qualità', 'Team specializzato'],
    introTitle: 'Eccellenza nei componenti industriali',
    introP1a: 'Aceros è la divisione acciai inossidabili del gruppo ', introP1b: 'Metalúrgica Daniela. Non commercializziamo commodity o tubi standard: la nostra fabbrica produce per centrifugazione pezzi in lega alta resistenti a calore, abrasione e ossidazione severa (ASTM A297), lavorati su disegno del cliente.',
    introP2a: 'La nostra ingegneria fornisce ', introP2b: 'boccole di estremità per Sink Roll (rulli nei pot di zinco per linee di zincatura) e componenti per Rulli da Forno (Furnace Rolls per trattamento termico), lavorati su disegno e condizioni operative indicate dal cliente.',
    specsTitle: 'Specifiche tecniche', specsCol1: 'Categoria', specsCol2: 'Dettagli disponibili',
    specRows: [
      ['Leghe disponibili', 'Leghe selezionate per applicazione, inclusi materiali secondo ASTM A297 se applicabili'],
      ['Processo produttivo', 'Fusione centrifugata o statica + lavorazione CNC di precisione'],
      ['Applicazioni speciali', 'Boccole di estremità Sink Roll e componenti Furnace Roll'],
      ['Dimensioni', 'Diametri e lunghezze su richiesta (produzione secondo progetto)'],
      ['Norme tecniche', 'ABNT, ASTM, DIN, AISI'],
      ['Ispezione', 'Tracciabilità e prove definite per la fornitura, comprese durezza, analisi chimica, ultrasuoni e liquidi penetranti se applicabili'],
    ],
    specsFooter: 'Consulta il nostro team tecnico per specifiche in linea con la tua esigenza.',
    differentialsTitle: 'Differenziali Aceros',
    differentialsLead: 'Capacità tecniche per la fabbricazione di boccole centrifugate su misura.',
    differentials: [
      { title: 'Pezzo in lega alta (non commodity)', text: 'Centrifugazione interna + ingegneria dei materiali + lavorazione CNC su misura.' },
      { title: 'Fabbricazione su misura', text: 'Produzione personalizzata secondo i requisiti esatti di montaggio.' },
      { title: 'Selezione delle leghe', text: 'Materiale definito in base ad abrasione, corrosione, temperatura e requisiti meccanici.' },
      { title: 'Controllo qualità', text: 'Ispezioni e prove definite secondo i requisiti della fornitura.' },
      { title: 'Assistenza tecnica', text: 'Supporto dell\'ingegneria nell\'analisi dell\'applicazione.' },
      { title: 'Produzione su progetto', text: 'Fabbricazione e lavorazione guidate dal disegno tecnico.' },
      { title: 'Soluzioni personalizzate', text: 'Sviluppo in base alle condizioni di servizio indicate dal cliente.' },
      { title: 'Brasile ed estero', text: 'Servizio commerciale per progetti nazionali e internazionali.' },
      { title: 'Applicazioni severe', text: 'Componenti sviluppati per condizioni termiche, meccaniche e chimiche specifiche.' },
    ],
    applicationsTitle: 'Principali applicazioni',
    applicationsLead: 'Applicazioni servite secondo disegno e requisiti operativi.',
    applicationLabels: ['Mineraria', 'Siderurgia', 'Sink Roll & estremità', 'Rulli da forno', 'Trattamento termico', 'Zincatura', 'Metallurgia'],
    applicationsFooter: 'Ogni progetto è analizzato secondo applicazione, disegno tecnico, materiale e requisiti di ispezione forniti dal cliente.',
    galleryTitle: 'Galleria prodotti',
    galleryAlts: [
      'Boccola in acciaio inossidabile lavorata su misura da Aceros',
      'Boccola centrifugata in acciaio inossidabile per applicazione industriale',
      'Boccola in acciaio inossidabile con finitura e lavorazione di alta precisione',
      'Boccola per estremità sink roll di Aceros',
      'Boccola in acciaio inossidabile in ispezione dimensionale',
      'Boccola in acciaio inossidabile pronta per la spedizione',
    ],
    processTitle: 'Il nostro processo',
    processSteps: [
      { title: 'Ricezione del progetto', desc: 'Analisi dettagliata dei requisiti forniti.' },
      { title: 'Analisi tecnica', desc: 'Validazione di tolleranze e fattibilità produttiva da parte dell\'ingegneria.' },
      { title: 'Definizione della lega', desc: 'Selezione del materiale in base alle condizioni di servizio e alla norma applicabile.' },
      { title: 'Fabbricazione', desc: 'Grezzo per centrifugazione e lavorazione CNC di precisione.' },
      { title: 'Controllo dimensionale', desc: 'Misura delle dimensioni e tolleranze indicate a disegno.' },
      { title: 'Ispezione di qualità', desc: 'Prove e verifiche definite secondo i requisiti della fornitura.' },
      { title: 'Consegna', desc: 'Spedizione protetta secondo le condizioni definite nell\'offerta.' },
    ],
    whyTitle: 'Perché scegliere Aceros',
    whyPoints: [
      'Divisione acciai inossidabili del Gruppo Metalúrgica Daniela',
      'Fabbricazione per centrifugazione in leghe ASTM A297, se applicabili',
      'Esperienza con componenti Sink Roll e Furnace Roll',
      'Sviluppo di componenti su misura (non commodity)',
      'Controllo e tracciabilità secondo i requisiti della fornitura',
      'Soluzioni per applicazioni con calore, abrasione e corrosione',
    ],
    isoBadge: 'Certificazione internazionale',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'certificata',
    isoLead: 'Il nostro Sistema di Gestione della Qualità è certificato DQS GmbH, con accreditamento DAkkS e riconoscimento della rete IQNet.',
    isoCertLabel: 'Certificato', isoValidLabel: 'Valido fino al',
    isoFooter: 'Secondo i requisiti della fornitura, la documentazione può includere tracciabilità, rapporto metallurgico, prove di durezza, analisi chimica e ultrasuoni.',
    ctaMidTitle: 'Serve una boccola in acciaio inossidabile?',
    ctaMidLead: 'Il nostro team tecnico valuta disegno e condizioni di servizio per orientare i prossimi passi del progetto.',
    ctaMidRequest: 'Richiedi preventivo', ctaMidWhatsapp: 'Invia progetto via WhatsApp',
    faqTitle: 'Domande frequenti',
    faqs: [
      { q: 'Quali sono i vantaggi delle boccole Sink Roll di Aceros?', a: 'Realizzate per centrifugazione e lavorate su disegno, sono destinate alle estremità dei Sink Roll e ad altre applicazioni industriali definite dalla condizione operativa.' },
      { q: 'Lavorate con commodity o tubi standard?', a: 'No. Aceros si concentra esclusivamente su ingegneria e produzione su misura di componenti in lega alta centrifugati e lavorati su disegno.' },
      { q: 'Qual è l\'applicazione delle boccole per Furnace Roll?', a: 'Sono componenti dimensionati secondo disegno e condizioni operative dei rulli utilizzati nei forni di trattamento termico.' },
      { q: 'Quali leghe di acciaio inossidabile utilizza Aceros?', a: 'La lega è selezionata dall\'ingegneria in base a temperatura, corrosione, abrasione e requisiti dimensionali del progetto, inclusi materiali secondo ASTM A297 se applicabili.' },
      { q: 'Aceros produce boccole su disegno tecnico?', a: 'Sì. Fabbricazione e lavorazione sono realizzate su misura in base al disegno tecnico e ai requisiti indicati dal cliente.' },
    ],
    formTitle: 'Richiedi il tuo preventivo di boccole',
    formLead1: 'Il nostro team tecnico analizza le informazioni del progetto e prepara la proposta commerciale.',
    formLead2: 'Risposta commerciale entro un giorno lavorativo.',
    formName: 'Nome completo', formNamePh: 'Il tuo nome',
    formCompany: 'Azienda', formCompanyPh: 'Nome azienda',
    formPhone: 'Telefono / WhatsApp',
    formCity: 'Città / Provincia', formCityPh: 'Città - Provincia',
    formEmail: 'E-mail aziendale', formEmailPh: 'email@azienda.it',
    formMaterial: 'Lega o materiale', formMaterialPh: 'Se noto',
    formDeadline: 'Tempo di consegna', formDeadlinePh: 'Es.: 60 giorni',
    formDimensions: 'Dimensioni e quantità', formDimensionsPh: 'Diametri, lunghezza e quantità',
    formDrawing: 'Disegno tecnico', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG o PNG, fino a 5 MB.',
    formMessage: 'Informazioni aggiuntive', formMessagePh: 'Indica applicazione, gruppo e altre condizioni operative.',
    formPrivacyA: 'Ho letto e accetto l\'', formPrivacyLink: 'Informativa sulla privacy', formPrivacyB: ' e autorizzo l\'uso dei dati per rispondere a questa richiesta.',
    formSubmitting: 'Invio in corso...', formSubmit: 'Richiedi preventivo',
    toastOkTitle: 'Richiesta ricevuta!', toastOkDesc: 'Il tuo messaggio è stato inviato. Il nostro team ti contatterà a breve.',
    toastErrTitle: 'Qualcosa è andato storto', toastErrDesc: 'Riprova o usa il pulsante WhatsApp per un\'assistenza immediata.',
    zoomAria: 'Ingrandisci',
    whatsappMessage: 'Ciao! Vorrei un preventivo per boccole in acciaio inossidabile su misura.',
  },
};
