import type { Language } from '@/hooks/use-language';

export type TubosCopy = {
  heroEyebrow: string; heroTitle: string; heroLead: string;
  ctaRequestQuote: string; ctaWhatsappTeam: string;
  strip: [string, string, string, string, string];
  introTitle: string; introP1: string; introP2: string;
  introImgAlt: string;
  specsTitle: string; specsCol1: string; specsCol2: string;
  specRows: Array<[string, string]>;
  specsFooter: string;
  differentialsTitle: string;
  differentials: Array<{ title: string; text: string }>;
  applicationsTitle: string; applicationsLead: string;
  applicationLabels: string[];
  galleryTitle: string; galleryLead: string; zoomAria: string;
  galleryAlts: string[];
  processTitle: string;
  processSteps: Array<{ title: string; desc: string }>;
  isoBadge: string; isoTitle1: string; isoTitleAccent: string; isoLead: string;
  isoCertLabel: string; isoValidLabel: string; isoFooter: string;
  ctaMidTitle: string; ctaMidLead: string; ctaMidRequest: string; ctaMidWhatsapp: string;
  faqTitle: string;
  faqs: Array<{ q: string; a: string }>;
  formTitle: string; formLead1: string; formLead2: string;
  formName: string; formNamePh: string; formCompany: string; formCompanyPh: string;
  formPhone: string; formCity: string; formCityPh: string;
  formEmail: string; formEmailPh: string;
  formMaterial: string; formMaterialPh: string;
  formDeadline: string; formDeadlinePh: string;
  formDimensions: string; formDimensionsPh: string;
  formDrawing: string; formDrawingHelp: string;
  formMessage: string; formMessagePh: string;
  formPrivacyA: string; formPrivacyLink: string; formPrivacyB: string;
  formSubmitting: string; formSubmit: string;
  toastOkTitle: string; toastOkDesc: string;
  toastErrTitle: string; toastErrDesc: string;
  whatsappMessage: string;
  heroImgAlt: string;
};

export const tubosCopy: Record<Language, TubosCopy> = {
  pt: {
    heroEyebrow: 'Fabricação industrial sob medida',
    heroTitle: 'Tubos de Aço Inox Fabricados Sob Medida para Aplicações Industriais',
    heroLead: 'Tubos mecânicos centrifugados em ligas selecionadas conforme temperatura, abrasão, corrosão e desenho técnico.',
    ctaRequestQuote: 'Solicitar Orçamento', ctaWhatsappTeam: 'Falar com a equipe técnica',
    strip: ['Fabricação sob medida', 'Conforme desenho técnico', 'Atendimento Brasil e exterior', 'Controle de qualidade', 'Equipe especializada'],
    introTitle: 'Tubos de Aço Inox para Projetos Industriais',
    introP1: 'A Aceros é fabricante brasileira de aços inoxidáveis centrifugados. Não comercializamos tubos comuns de prateleira ou commodities: nossa fábrica produz via processo de centrifugação sob medida em ligas especiais resistentes a calor, abrasão e oxidação severa (norma ASTM A297).',
    introP2: 'O processo de centrifugação favorece uma estrutura densa e o controle da geometria tubular. Cada projeto é avaliado pela engenharia para que a liga, as dimensões e o acabamento correspondam às condições de operação informadas pelo cliente.',
    introImgAlt: 'Tubo centrifugado de alta liga em processo de usinagem',
    specsTitle: 'Especificações Técnicas', specsCol1: 'Categoria', specsCol2: 'Detalhes Disponíveis',
    specRows: [
      ['Ligas Disponíveis', 'Ligas especiais selecionadas conforme a aplicação, incluindo materiais conforme ASTM A297 quando aplicável'],
      ['Processo Produtivo', 'Fundição por Centrifugação (Centrifugal Casting) e Estática'],
      ['Estágios de Acabamento', 'Bruto de centrifugação, Usinado (Munhão), Polido/Acabado ou Misto'],
      ['Dimensões', 'Diâmetros, espessuras e comprimentos fabricados 100% sob medida'],
      ['Normas Técnicas', 'ABNT, ASTM, DIN, AISI'],
      ['Inspeção', 'Rastreabilidade e ensaios definidos para o fornecimento, incluindo dureza, análise química e ultrassom quando aplicáveis'],
    ],
    specsFooter: 'Consulte nossa equipe técnica para especificações conforme sua necessidade.',
    differentialsTitle: 'Diferenciais Aceros em Tubos',
    differentials: [
      { title: 'Fabricação sob medida', text: 'Geometrias, dimensões e acabamento definidos conforme o desenho técnico.' },
      { title: 'Seleção de ligas', text: 'Material especificado conforme temperatura, abrasão, corrosão e demais condições de serviço.' },
      { title: 'Aplicações de alta temperatura', text: 'Tubos desenvolvidos para fornos e processos térmicos industriais.' },
      { title: 'Processo de Centrifugação', text: 'Processo que favorece maior densidade estrutural e concentricidade da peça tubular.' },
      { title: 'Gestão da qualidade', text: 'Sistema de Gestão da Qualidade certificado conforme ISO 9001:2015.' },
      { title: 'Projeto para a condição de serviço', text: 'Parâmetros de fabricação avaliados conforme os requisitos informados pelo cliente.' },
      { title: 'Usinagem conforme desenho', text: 'Acabamento e tolerâncias dimensionais definidos pelo projeto.' },
      { title: 'Brasil e exterior', text: 'Atendimento comercial para projetos nacionais e internacionais.' },
      { title: 'Engenharia de Materiais', text: 'Apoio técnico para selecionar a liga adequada à aplicação.' },
    ],
    applicationsTitle: 'Setores Atendidos',
    applicationsLead: 'Aplicações atendidas conforme desenho e requisitos de operação.',
    applicationLabels: ['Siderurgia', 'Mineração', 'Tratamento Térmico', 'Galvanização', 'Indústria Guseira', 'Setor Naval', 'Metalurgia'],
    galleryTitle: 'Galeria Técnica e Evolução de Acabamento',
    galleryLead: 'Do bruto de centrifugação à peça polida: veja a qualidade Aceros em cada estágio.',
    zoomAria: 'Ampliar',
    galleryAlts: [
      'Tubo centrifugado bruto de aço inox, como sai do processo de fundição',
      'Tubo de aço inox bruto pronto para usinagem',
      'Tubo de aço inox após usinagem de precisão CNC',
      'Tubo de aço inox usinado, usinagem da ponta (munhão)',
      'Tubo de aço inox usinado e polido, peça acabada com revenido',
      'Tubo de aço inox polido, acabamento espelhado',
      'Tubo de aço inox, peça acabada em inspeção dimensional',
      'Tubo de aço inox com acabamento misto (usinado + polido)',
    ],
    processTitle: 'Processo de Fabricação',
    processSteps: [
      { title: 'Recebimento do Projeto', desc: 'Análise dos requisitos dimensionais e operacionais.' },
      { title: 'Análise Técnica', desc: 'Nossa engenharia valida a viabilidade de fabricação.' },
      { title: 'Definição da Liga', desc: 'Seleção do material conforme as condições de serviço e a norma aplicável.' },
      { title: 'Processo de Fabricação', desc: 'Centrifugação da peça bruta com parâmetros definidos para seu diâmetro e massa.' },
      { title: 'Controle Dimensional', desc: 'Medição precisa para garantir as tolerâncias do projeto.' },
      { title: 'Inspeção de Qualidade', desc: 'Ensaios e verificações definidos conforme os requisitos do fornecimento.' },
      { title: 'Entrega', desc: 'Expedição protegida para indústrias em todo o Brasil.' },
    ],
    isoBadge: 'Certificação Internacional',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'Certificada',
    isoLead: 'Nosso Sistema de Gestão da Qualidade é certificado pela DQS GmbH, com acreditação DAkkS e reconhecimento da rede IQNet.',
    isoCertLabel: 'Certificado', isoValidLabel: 'Válido até',
    isoFooter: 'Conforme os requisitos do fornecimento, a documentação pode incluir rastreabilidade, laudo metalúrgico, ensaios de dureza, análise química e ultrassom.',
    ctaMidTitle: 'Precisa de Tubos de Aço Inox para sua indústria?',
    ctaMidLead: 'Nossa equipe técnica avalia o desenho e as condições de serviço para orientar os próximos passos do projeto.',
    ctaMidRequest: 'Solicitar Cotação', ctaMidWhatsapp: 'Enviar Projeto via WhatsApp',
    faqTitle: 'Perguntas Frequentes',
    faqs: [
      { q: 'Quais as vantagens dos tubos centrifugados da Aceros?', a: 'Diferente de tubos comuns de prateleira, nossos tubos centrifugados são fabricados sob medida. O processo favorece uma estrutura densa e permite definir dimensões, liga e acabamento conforme a aplicação industrial.' },
      { q: 'Quais são os estágios de acabamento oferecidos pela fábrica?', a: 'Oferecemos 4 estágios conforme seu projeto: 1. Bruto de centrifugação (alta densidade); 2. Usinado (munhão e corpo acetinado); 3. Polido/Acabado (peça espelhada com revenido térmico); 4. Misto (fornecimento sob demanda).' },
      { q: 'A Aceros trabalha com produtos commodities?', a: 'Não. Somos uma fábrica focada exclusivamente em engenharia e fabricação sob medida de componentes de alta liga centrifugados e usinados conforme desenho técnico.' },
      { q: 'Quais as dimensões e ligas disponíveis?', a: 'A liga é selecionada conforme a temperatura, abrasão, corrosão e demais condições de serviço. Diâmetro, espessura e comprimento são definidos conforme o desenho técnico do projeto.' },
      { q: 'Atendem pedidos para o Brasil e exterior?', a: 'Sim. Atendemos projetos no Brasil e no exterior. Condições de entrega e prazos são confirmados na proposta comercial.' },
    ],
    formTitle: 'Solicite seu Orçamento de Tubos',
    formLead1: 'Nossa equipe técnica analisa as informações do projeto e prepara a proposta comercial.',
    formLead2: 'Retorno comercial em até um dia útil.',
    formName: 'Nome Completo', formNamePh: 'Seu nome',
    formCompany: 'Empresa', formCompanyPh: 'Nome da empresa',
    formPhone: 'Telefone / WhatsApp',
    formCity: 'Cidade / UF', formCityPh: 'Cidade - UF',
    formEmail: 'E-mail Corporativo', formEmailPh: 'email@empresa.com.br',
    formMaterial: 'Liga ou material', formMaterialPh: 'Se conhecido',
    formDeadline: 'Prazo desejado', formDeadlinePh: 'Ex.: 60 dias',
    formDimensions: 'Dimensões e quantidade', formDimensionsPh: 'Diâmetro, espessura, comprimento e quantidade',
    formDrawing: 'Desenho técnico', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG ou PNG, até 5 MB.',
    formMessage: 'Informações adicionais', formMessagePh: 'Informe a aplicação, a temperatura e outras condições de operação.',
    formPrivacyA: 'Li e aceito a ', formPrivacyLink: 'Política de Privacidade', formPrivacyB: ' e autorizo o uso dos dados para retorno desta solicitação.',
    formSubmitting: 'Enviando...', formSubmit: 'Solicitar Orçamento',
    toastOkTitle: 'Solicitação Enviada!', toastOkDesc: 'Sua mensagem foi enviada com sucesso. Nossa equipe entrará em contato em breve.',
    toastErrTitle: 'Erro no envio', toastErrDesc: 'Tente novamente ou fale conosco diretamente pelo WhatsApp para agilizar sua cotação.',
    whatsappMessage: 'Olá! Gostaria de solicitar um orçamento de tubos de aço inox.',
    heroImgAlt: 'Tubo de aço inox centrifugado, usinado e polido, fabricação Aceros',
  },
  en: {
    heroEyebrow: 'Custom industrial manufacturing',
    heroTitle: 'Custom Stainless Steel Tubes for Industrial Applications',
    heroLead: 'Centrifugally cast mechanical tubes in alloys selected for temperature, abrasion, corrosion and technical drawing.',
    ctaRequestQuote: 'Request a quote', ctaWhatsappTeam: 'Talk to the technical team',
    strip: ['Custom manufacturing', 'Made to drawing', 'Serving Brazil and abroad', 'Quality control', 'Specialised team'],
    introTitle: 'Stainless steel tubes for industrial projects',
    introP1: 'Aceros is a Brazilian stainless steel centrifugal casting manufacturer. We do not sell off-the-shelf tubes or commodities: our shop produces custom centrifugally cast parts in special alloys resistant to heat, abrasion and severe oxidation (ASTM A297).',
    introP2: 'Centrifugal casting favours a dense structure and control of tube geometry. Every project is reviewed by engineering so that alloy, dimensions and finish match the operating conditions provided by the customer.',
    introImgAlt: 'High-alloy centrifugally cast tube being machined',
    specsTitle: 'Technical specifications', specsCol1: 'Category', specsCol2: 'Available details',
    specRows: [
      ['Available alloys', 'Special alloys selected per application, including materials to ASTM A297 where applicable'],
      ['Manufacturing process', 'Centrifugal casting and static casting'],
      ['Finish stages', 'As-cast, machined (trunnion), polished/finished or mixed'],
      ['Dimensions', 'Diameters, wall thickness and lengths 100% made-to-measure'],
      ['Technical standards', 'ABNT, ASTM, DIN, AISI'],
      ['Inspection', 'Traceability and tests defined per supply, including hardness, chemical analysis and ultrasound when applicable'],
    ],
    specsFooter: 'Consult our technical team for specifications matched to your needs.',
    differentialsTitle: 'Aceros differentials in tubes',
    differentials: [
      { title: 'Custom manufacturing', text: 'Geometries, dimensions and finish defined by the technical drawing.' },
      { title: 'Alloy selection', text: 'Material specified per temperature, abrasion, corrosion and service conditions.' },
      { title: 'High-temperature applications', text: 'Tubes engineered for furnaces and industrial thermal processes.' },
      { title: 'Centrifugal casting', text: 'Process that favours higher structural density and concentricity of the tubular part.' },
      { title: 'Quality management', text: 'Quality Management System certified to ISO 9001:2015.' },
      { title: 'Designed for the duty cycle', text: 'Manufacturing parameters assessed per the requirements provided by the customer.' },
      { title: 'Machining to drawing', text: 'Finish and dimensional tolerances defined by the project.' },
      { title: 'Brazil and abroad', text: 'Commercial support for domestic and international projects.' },
      { title: 'Materials engineering', text: 'Technical support in selecting the alloy for the application.' },
    ],
    applicationsTitle: 'Sectors served',
    applicationsLead: 'Applications served according to drawing and operating requirements.',
    applicationLabels: ['Steelmaking', 'Mining', 'Heat treatment', 'Galvanising', 'Pig-iron industry', 'Naval sector', 'Metallurgy'],
    galleryTitle: 'Technical gallery and finish evolution',
    galleryLead: 'From as-cast to polished: the Aceros quality at every stage.',
    zoomAria: 'Enlarge',
    galleryAlts: [
      'As-cast centrifugally cast stainless steel tube',
      'Rough stainless steel tube ready for machining',
      'Stainless steel tube after CNC precision machining',
      'Stainless steel tube with trunnion machining',
      'Machined and polished stainless steel tube, finished with tempering',
      'Polished stainless steel tube with mirror finish',
      'Stainless steel tube under dimensional inspection',
      'Stainless steel tube with mixed finish (machined + polished)',
    ],
    processTitle: 'Manufacturing process',
    processSteps: [
      { title: 'Project intake', desc: 'Review of dimensional and operational requirements.' },
      { title: 'Technical analysis', desc: 'Our engineering confirms manufacturability.' },
      { title: 'Alloy definition', desc: 'Material selection per service conditions and applicable standard.' },
      { title: 'Manufacturing', desc: 'Rough part centrifugally cast with parameters defined for its diameter and mass.' },
      { title: 'Dimensional control', desc: 'Precise measurement to ensure project tolerances.' },
      { title: 'Quality inspection', desc: 'Tests and checks defined per supply requirements.' },
      { title: 'Delivery', desc: 'Protected shipment to industry across Brazil.' },
    ],
    isoBadge: 'International certification',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'Certified',
    isoLead: 'Our Quality Management System is certified by DQS GmbH, with DAkkS accreditation and IQNet network recognition.',
    isoCertLabel: 'Certificate', isoValidLabel: 'Valid through',
    isoFooter: 'According to supply requirements, documentation may include traceability, metallurgical report, hardness tests, chemical analysis and ultrasound.',
    ctaMidTitle: 'Need stainless steel tubes for your plant?',
    ctaMidLead: 'Our technical team reviews the drawing and service conditions to advise the next steps of the project.',
    ctaMidRequest: 'Request a quote', ctaMidWhatsapp: 'Send the project on WhatsApp',
    faqTitle: 'Frequently asked questions',
    faqs: [
      { q: 'What are the advantages of Aceros centrifugally cast tubes?', a: 'Unlike off-the-shelf tubes, ours are made to order. The process favours a dense structure and lets us define dimensions, alloy and finish for the industrial application.' },
      { q: 'Which finish stages does the shop offer?', a: 'Four stages depending on your project: 1. As-cast (high density); 2. Machined (trunnion and satin body); 3. Polished/finished (mirror surface with thermal tempering); 4. Mixed (on demand).' },
      { q: 'Does Aceros deal with commodities?', a: 'No. We are a factory focused exclusively on custom engineering and manufacturing of high-alloy centrifugally cast components machined to drawing.' },
      { q: 'Which dimensions and alloys are available?', a: 'The alloy is selected based on temperature, abrasion, corrosion and other service conditions. Diameter, wall thickness and length are defined by the project drawing.' },
      { q: 'Do you serve orders in Brazil and abroad?', a: 'Yes. We serve projects in Brazil and abroad. Delivery conditions and lead times are confirmed in the commercial proposal.' },
    ],
    formTitle: 'Request your tube quote',
    formLead1: 'Our technical team reviews the project information and prepares the commercial proposal.',
    formLead2: 'Commercial reply within one business day.',
    formName: 'Full name', formNamePh: 'Your name',
    formCompany: 'Company', formCompanyPh: 'Company name',
    formPhone: 'Phone / WhatsApp',
    formCity: 'City / State', formCityPh: 'City - State',
    formEmail: 'Business e-mail', formEmailPh: 'email@company.com',
    formMaterial: 'Alloy or material', formMaterialPh: 'If known',
    formDeadline: 'Desired lead time', formDeadlinePh: 'E.g. 60 days',
    formDimensions: 'Dimensions and quantity', formDimensionsPh: 'Diameter, wall thickness, length and quantity',
    formDrawing: 'Technical drawing', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG or PNG, up to 5 MB.',
    formMessage: 'Additional information', formMessagePh: 'Share the application, temperature and other operating conditions.',
    formPrivacyA: 'I have read and accept the ', formPrivacyLink: 'Privacy Policy', formPrivacyB: ' and authorise the use of my data to reply to this request.',
    formSubmitting: 'Sending...', formSubmit: 'Request a quote',
    toastOkTitle: 'Request submitted!', toastOkDesc: 'Your message has been sent. Our team will get in touch shortly.',
    toastErrTitle: 'Sending failed', toastErrDesc: 'Please try again or reach us on WhatsApp for a faster quote.',
    whatsappMessage: 'Hi! I would like a quote for stainless steel tubes.',
    heroImgAlt: 'Aceros centrifugally cast, machined and polished stainless steel tube',
  },
  es: {
    heroEyebrow: 'Fabricación industrial a medida',
    heroTitle: 'Tubos de Acero Inoxidable a Medida para Aplicaciones Industriales',
    heroLead: 'Tubos mecánicos centrifugados en aleaciones seleccionadas según temperatura, abrasión, corrosión y plano técnico.',
    ctaRequestQuote: 'Solicitar presupuesto', ctaWhatsappTeam: 'Hablar con el equipo técnico',
    strip: ['Fabricación a medida', 'Según plano técnico', 'Atención Brasil y exterior', 'Control de calidad', 'Equipo especializado'],
    introTitle: 'Tubos de acero inoxidable para proyectos industriales',
    introP1: 'Aceros es fabricante brasileña de aceros inoxidables centrifugados. No comercializamos tubos comunes de estantería ni commodities: nuestra fábrica produce por centrifugación a medida piezas en aleaciones especiales resistentes a calor, abrasión y oxidación severa (ASTM A297).',
    introP2: 'La centrifugación favorece una estructura densa y el control de la geometría tubular. Cada proyecto es analizado por ingeniería para que la aleación, las dimensiones y el acabado correspondan a las condiciones de operación indicadas por el cliente.',
    introImgAlt: 'Tubo centrifugado de alta aleación en proceso de mecanizado',
    specsTitle: 'Especificaciones técnicas', specsCol1: 'Categoría', specsCol2: 'Detalles disponibles',
    specRows: [
      ['Aleaciones disponibles', 'Aleaciones especiales seleccionadas según la aplicación, incluidos materiales según ASTM A297 cuando aplique'],
      ['Proceso productivo', 'Fundición centrifugada y estática'],
      ['Etapas de acabado', 'En bruto de centrifugación, mecanizado (muñón), pulido/acabado o mixto'],
      ['Dimensiones', 'Diámetros, espesores y longitudes 100% a medida'],
      ['Normas técnicas', 'ABNT, ASTM, DIN, AISI'],
      ['Inspección', 'Trazabilidad y ensayos definidos para el suministro, incluidos dureza, análisis químico y ultrasonido cuando aplique'],
    ],
    specsFooter: 'Consulte a nuestro equipo técnico para especificaciones según su necesidad.',
    differentialsTitle: 'Diferenciales Aceros en Tubos',
    differentials: [
      { title: 'Fabricación a medida', text: 'Geometrías, dimensiones y acabado definidos según el plano técnico.' },
      { title: 'Selección de aleaciones', text: 'Material especificado según temperatura, abrasión, corrosión y condiciones de servicio.' },
      { title: 'Aplicaciones de alta temperatura', text: 'Tubos desarrollados para hornos y procesos térmicos industriales.' },
      { title: 'Proceso de centrifugación', text: 'Proceso que favorece mayor densidad estructural y concentricidad del tubo.' },
      { title: 'Gestión de la calidad', text: 'Sistema de Gestión de la Calidad certificado según ISO 9001:2015.' },
      { title: 'Proyecto para la condición de servicio', text: 'Parámetros de fabricación evaluados según los requisitos indicados por el cliente.' },
      { title: 'Mecanizado según plano', text: 'Acabado y tolerancias dimensionales definidos por el proyecto.' },
      { title: 'Brasil y exterior', text: 'Atención comercial para proyectos nacionales e internacionales.' },
      { title: 'Ingeniería de materiales', text: 'Apoyo técnico para seleccionar la aleación adecuada.' },
    ],
    applicationsTitle: 'Sectores atendidos',
    applicationsLead: 'Aplicaciones atendidas según plano y requisitos de operación.',
    applicationLabels: ['Siderurgia', 'Minería', 'Tratamiento térmico', 'Galvanizado', 'Industria del arrabio', 'Sector naval', 'Metalurgia'],
    galleryTitle: 'Galería técnica y evolución del acabado',
    galleryLead: 'Del bruto de centrifugación a la pieza pulida: la calidad Aceros en cada etapa.',
    zoomAria: 'Ampliar',
    galleryAlts: [
      'Tubo centrifugado en bruto, tal como sale del proceso de fundición',
      'Tubo de acero inoxidable en bruto listo para mecanizar',
      'Tubo de acero inoxidable tras mecanizado CNC de precisión',
      'Tubo de acero inoxidable con mecanizado del muñón',
      'Tubo de acero inoxidable mecanizado y pulido, acabado con revenido',
      'Tubo de acero inoxidable pulido, acabado espejo',
      'Tubo de acero inoxidable en inspección dimensional',
      'Tubo de acero inoxidable con acabado mixto (mecanizado + pulido)',
    ],
    processTitle: 'Proceso de fabricación',
    processSteps: [
      { title: 'Recepción del proyecto', desc: 'Análisis de los requisitos dimensionales y operativos.' },
      { title: 'Análisis técnico', desc: 'Nuestra ingeniería valida la viabilidad de fabricación.' },
      { title: 'Definición de la aleación', desc: 'Selección del material según las condiciones de servicio y la norma aplicable.' },
      { title: 'Proceso de fabricación', desc: 'Centrifugación del bruto con parámetros definidos para su diámetro y masa.' },
      { title: 'Control dimensional', desc: 'Medición precisa para garantizar las tolerancias del proyecto.' },
      { title: 'Inspección de calidad', desc: 'Ensayos y verificaciones definidos según los requisitos del suministro.' },
      { title: 'Entrega', desc: 'Expedición protegida para industrias en todo Brasil.' },
    ],
    isoBadge: 'Certificación internacional',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'Certificada',
    isoLead: 'Nuestro Sistema de Gestión de la Calidad está certificado por DQS GmbH, con acreditación DAkkS y reconocimiento de la red IQNet.',
    isoCertLabel: 'Certificado', isoValidLabel: 'Válido hasta',
    isoFooter: 'Según los requisitos del suministro, la documentación puede incluir trazabilidad, informe metalúrgico, ensayos de dureza, análisis químico y ultrasonido.',
    ctaMidTitle: '¿Necesita tubos de acero inoxidable para su industria?',
    ctaMidLead: 'Nuestro equipo técnico evalúa el plano y las condiciones de servicio para orientar los próximos pasos del proyecto.',
    ctaMidRequest: 'Solicitar cotización', ctaMidWhatsapp: 'Enviar proyecto por WhatsApp',
    faqTitle: 'Preguntas frecuentes',
    faqs: [
      { q: '¿Cuáles son las ventajas de los tubos centrifugados de Aceros?', a: 'A diferencia de los tubos comunes de estantería, los nuestros se fabrican a medida. El proceso favorece una estructura densa y permite definir dimensiones, aleación y acabado según la aplicación industrial.' },
      { q: '¿Qué etapas de acabado ofrece la fábrica?', a: 'Ofrecemos 4 etapas según su proyecto: 1. Bruto de centrifugación (alta densidad); 2. Mecanizado (muñón y cuerpo satinado); 3. Pulido/acabado (pieza espejo con revenido térmico); 4. Mixto (bajo demanda).' },
      { q: '¿Aceros trabaja con commodities?', a: 'No. Somos una fábrica enfocada exclusivamente en ingeniería y fabricación a medida de componentes de alta aleación centrifugados y mecanizados según plano técnico.' },
      { q: '¿Qué dimensiones y aleaciones están disponibles?', a: 'La aleación se selecciona según temperatura, abrasión, corrosión y demás condiciones de servicio. Diámetro, espesor y longitud se definen según el plano técnico del proyecto.' },
      { q: '¿Atienden pedidos en Brasil y en el exterior?', a: 'Sí. Atendemos proyectos en Brasil y en el exterior. Condiciones de entrega y plazos se confirman en la propuesta comercial.' },
    ],
    formTitle: 'Solicite su cotización de tubos',
    formLead1: 'Nuestro equipo técnico analiza la información del proyecto y prepara la propuesta comercial.',
    formLead2: 'Respuesta comercial en un día hábil.',
    formName: 'Nombre completo', formNamePh: 'Su nombre',
    formCompany: 'Empresa', formCompanyPh: 'Nombre de la empresa',
    formPhone: 'Teléfono / WhatsApp',
    formCity: 'Ciudad / Estado', formCityPh: 'Ciudad - Estado',
    formEmail: 'E-mail corporativo', formEmailPh: 'email@empresa.com',
    formMaterial: 'Aleación o material', formMaterialPh: 'Si se conoce',
    formDeadline: 'Plazo deseado', formDeadlinePh: 'Ej.: 60 días',
    formDimensions: 'Dimensiones y cantidad', formDimensionsPh: 'Diámetro, espesor, longitud y cantidad',
    formDrawing: 'Plano técnico', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG o PNG, hasta 5 MB.',
    formMessage: 'Información adicional', formMessagePh: 'Indique la aplicación, la temperatura y otras condiciones de operación.',
    formPrivacyA: 'He leído y acepto la ', formPrivacyLink: 'Política de Privacidad', formPrivacyB: ' y autorizo el uso de los datos para responder a esta solicitud.',
    formSubmitting: 'Enviando...', formSubmit: 'Solicitar presupuesto',
    toastOkTitle: '¡Solicitud enviada!', toastOkDesc: 'Su mensaje fue enviado con éxito. Nuestro equipo se pondrá en contacto en breve.',
    toastErrTitle: 'Error al enviar', toastErrDesc: 'Intente de nuevo o hable con nosotros por WhatsApp para agilizar su cotización.',
    whatsappMessage: '¡Hola! Quisiera solicitar un presupuesto de tubos de acero inoxidable.',
    heroImgAlt: 'Tubo de acero inoxidable centrifugado, mecanizado y pulido de Aceros',
  },
  de: {
    heroEyebrow: 'Kundenspezifische Industriefertigung',
    heroTitle: 'Edelstahlrohre nach Maß für industrielle Anwendungen',
    heroLead: 'Schleudergegossene mechanische Rohre in Legierungen, ausgewählt nach Temperatur, Verschleiß, Korrosion und Zeichnung.',
    ctaRequestQuote: 'Angebot anfordern', ctaWhatsappTeam: 'Mit dem technischen Team sprechen',
    strip: ['Fertigung nach Maß', 'Nach technischer Zeichnung', 'Brasilien und international', 'Qualitätskontrolle', 'Spezialistenteam'],
    introTitle: 'Edelstahlrohre für industrielle Projekte',
    introP1: 'Aceros ist ein brasilianischer Hersteller von schleudergegossenem Edelstahl. Wir vertreiben keine Standardrohre oder Standardware: Unser Werk fertigt im Schleuderguss nach Maß aus Speziallegierungen, beständig gegen Hitze, Verschleiß und starke Oxidation (ASTM A297).',
    introP2: 'Der Schleuderguss fördert ein dichtes Gefüge und die Kontrolle der Rohrgeometrie. Jedes Projekt wird von der Konstruktion so bewertet, dass Legierung, Abmessungen und Ausführung den vom Kunden angegebenen Betriebsbedingungen entsprechen.',
    introImgAlt: 'Hochlegiertes Schleudergussrohr in der Bearbeitung',
    specsTitle: 'Technische Spezifikationen', specsCol1: 'Kategorie', specsCol2: 'Verfügbare Details',
    specRows: [
      ['Verfügbare Legierungen', 'Speziallegierungen nach Anwendung, u. a. Werkstoffe nach ASTM A297, wo zutreffend'],
      ['Fertigungsprozess', 'Schleuderguss und statischer Guss'],
      ['Ausführungsstufen', 'Rohguss, bearbeitet (Zapfen), poliert/fertig oder gemischt'],
      ['Abmessungen', 'Durchmesser, Wandstärken und Längen zu 100 % nach Maß'],
      ['Technische Normen', 'ABNT, ASTM, DIN, AISI'],
      ['Prüfung', 'Rückverfolgbarkeit und Prüfungen nach Lieferumfang, u. a. Härte, chemische Analyse und Ultraschall, wo anwendbar'],
    ],
    specsFooter: 'Für Spezifikationen nach Ihrem Bedarf sprechen Sie mit unserem Technik-Team.',
    differentialsTitle: 'Aceros-Vorteile bei Rohren',
    differentials: [
      { title: 'Fertigung nach Maß', text: 'Geometrien, Abmessungen und Ausführung nach der technischen Zeichnung.' },
      { title: 'Legierungswahl', text: 'Werkstoff nach Temperatur, Verschleiß, Korrosion und weiteren Einsatzbedingungen.' },
      { title: 'Hochtemperatureinsätze', text: 'Rohre für Öfen und industrielle Wärmeprozesse ausgelegt.' },
      { title: 'Schleudergussverfahren', text: 'Verfahren mit höherer Dichte und Konzentrizität des Rohrs.' },
      { title: 'Qualitätsmanagement', text: 'Managementsystem zertifiziert nach ISO 9001:2015.' },
      { title: 'Auslegung für die Einsatzbedingung', text: 'Fertigungsparameter nach den vom Kunden angegebenen Anforderungen bewertet.' },
      { title: 'Bearbeitung nach Zeichnung', text: 'Ausführung und Maßtoleranzen aus dem Projekt.' },
      { title: 'Brasilien und Ausland', text: 'Kommerzielle Betreuung für nationale und internationale Projekte.' },
      { title: 'Werkstofftechnik', text: 'Technischer Support zur Auswahl der passenden Legierung.' },
    ],
    applicationsTitle: 'Betreute Branchen',
    applicationsLead: 'Anwendungen bedient nach Zeichnung und Betriebsanforderungen.',
    applicationLabels: ['Stahl', 'Bergbau', 'Wärmebehandlung', 'Verzinkung', 'Roheisenindustrie', 'Marine', 'Metallurgie'],
    galleryTitle: 'Technische Galerie und Ausführungsstufen',
    galleryLead: 'Vom Rohguss bis zum polierten Teil: Aceros-Qualität in jeder Stufe.',
    zoomAria: 'Vergrößern',
    galleryAlts: [
      'Rohes Schleudergussrohr direkt aus dem Guss',
      'Rohes Edelstahlrohr bereit zur Bearbeitung',
      'Edelstahlrohr nach CNC-Präzisionsbearbeitung',
      'Edelstahlrohr mit Zapfenbearbeitung',
      'Bearbeitetes und poliertes Edelstahlrohr, angelassen',
      'Poliertes Edelstahlrohr mit Spiegelfinish',
      'Edelstahlrohr in der Maßprüfung',
      'Edelstahlrohr mit gemischter Ausführung (bearbeitet + poliert)',
    ],
    processTitle: 'Fertigungsprozess',
    processSteps: [
      { title: 'Projektannahme', desc: 'Prüfung der Maß- und Betriebsanforderungen.' },
      { title: 'Technische Analyse', desc: 'Unsere Konstruktion prüft die Fertigbarkeit.' },
      { title: 'Legierungsdefinition', desc: 'Werkstoffwahl nach Einsatzbedingungen und geltender Norm.' },
      { title: 'Fertigung', desc: 'Rohteil im Schleuderguss mit passenden Parametern für Durchmesser und Masse.' },
      { title: 'Maßkontrolle', desc: 'Präzise Messung zur Sicherung der Projekttoleranzen.' },
      { title: 'Qualitätsprüfung', desc: 'Prüfungen und Kontrollen nach Liefervorgaben.' },
      { title: 'Lieferung', desc: 'Geschützter Versand an Industrie in ganz Brasilien.' },
    ],
    isoBadge: 'Internationale Zertifizierung',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'zertifiziert',
    isoLead: 'Unser Qualitätsmanagementsystem ist von DQS GmbH zertifiziert, mit DAkkS-Akkreditierung und IQNet-Anerkennung.',
    isoCertLabel: 'Zertifikat', isoValidLabel: 'Gültig bis',
    isoFooter: 'Je nach Lieferanforderungen kann die Dokumentation Rückverfolgbarkeit, metallurgischen Bericht, Härteprüfung, chemische Analyse und Ultraschall enthalten.',
    ctaMidTitle: 'Brauchen Sie Edelstahlrohre für Ihre Anlage?',
    ctaMidLead: 'Unser Technik-Team prüft Zeichnung und Einsatzbedingungen und schlägt die nächsten Schritte des Projekts vor.',
    ctaMidRequest: 'Angebot anfordern', ctaMidWhatsapp: 'Projekt per WhatsApp senden',
    faqTitle: 'Häufige Fragen',
    faqs: [
      { q: 'Welche Vorteile bieten Aceros-Schleudergussrohre?', a: 'Im Gegensatz zu Standardrohren werden unsere Rohre nach Maß gefertigt. Das Verfahren fördert ein dichtes Gefüge und erlaubt die Auslegung von Abmessungen, Legierung und Ausführung nach industrieller Anwendung.' },
      { q: 'Welche Ausführungsstufen bietet das Werk an?', a: 'Vier Stufen: 1. Rohguss (hohe Dichte); 2. Bearbeitet (Zapfen und satiniertes Rohr); 3. Poliert/fertig (Spiegelfinish mit Anlassen); 4. Gemischt (auf Anfrage).' },
      { q: 'Arbeitet Aceros mit Standardware?', a: 'Nein. Wir sind ein Werk, das ausschließlich auf Konstruktion und Fertigung nach Maß von hochlegierten Schleudergussteilen nach Zeichnung fokussiert ist.' },
      { q: 'Welche Abmessungen und Legierungen sind verfügbar?', a: 'Die Legierung wird nach Temperatur, Verschleiß, Korrosion und weiteren Einsatzbedingungen gewählt. Durchmesser, Wandstärke und Länge werden nach der technischen Zeichnung definiert.' },
      { q: 'Beliefern Sie Brasilien und das Ausland?', a: 'Ja. Wir betreuen Projekte in Brasilien und im Ausland. Lieferbedingungen und -fristen werden im Angebot bestätigt.' },
    ],
    formTitle: 'Angebot für Rohre anfragen',
    formLead1: 'Unser Technik-Team prüft die Projektangaben und erstellt das Angebot.',
    formLead2: 'Kaufmännische Antwort innerhalb eines Werktags.',
    formName: 'Vollständiger Name', formNamePh: 'Ihr Name',
    formCompany: 'Unternehmen', formCompanyPh: 'Firmenname',
    formPhone: 'Telefon / WhatsApp',
    formCity: 'Ort / Land', formCityPh: 'Ort - Land',
    formEmail: 'Geschäftliche E-Mail', formEmailPh: 'email@firma.de',
    formMaterial: 'Legierung oder Werkstoff', formMaterialPh: 'Falls bekannt',
    formDeadline: 'Gewünschte Lieferzeit', formDeadlinePh: 'z. B. 60 Tage',
    formDimensions: 'Abmessungen und Menge', formDimensionsPh: 'Durchmesser, Wandstärke, Länge und Menge',
    formDrawing: 'Technische Zeichnung', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG oder PNG, bis 5 MB.',
    formMessage: 'Weitere Angaben', formMessagePh: 'Bitte Anwendung, Temperatur und weitere Betriebsbedingungen angeben.',
    formPrivacyA: 'Ich habe die ', formPrivacyLink: 'Datenschutzerklärung', formPrivacyB: ' gelesen und akzeptiert und stimme der Nutzung meiner Daten zur Beantwortung dieser Anfrage zu.',
    formSubmitting: 'Wird gesendet...', formSubmit: 'Angebot anfordern',
    toastOkTitle: 'Anfrage gesendet!', toastOkDesc: 'Ihre Nachricht wurde gesendet. Unser Team meldet sich in Kürze.',
    toastErrTitle: 'Senden fehlgeschlagen', toastErrDesc: 'Bitte erneut versuchen oder auf WhatsApp schreiben, um das Angebot zu beschleunigen.',
    whatsappMessage: 'Hallo! Ich möchte ein Angebot für Edelstahlrohre anfragen.',
    heroImgAlt: 'Schleudergegossenes, bearbeitetes und poliertes Edelstahlrohr von Aceros',
  },
  it: {
    heroEyebrow: 'Fabbricazione industriale su misura',
    heroTitle: 'Tubi in acciaio inossidabile su misura per applicazioni industriali',
    heroLead: 'Tubi meccanici centrifugati in leghe selezionate per temperatura, abrasione, corrosione e disegno tecnico.',
    ctaRequestQuote: 'Richiedi preventivo', ctaWhatsappTeam: 'Parla con il team tecnico',
    strip: ['Fabbricazione su misura', 'Su disegno tecnico', 'Servizio Brasile ed estero', 'Controllo qualità', 'Team specializzato'],
    introTitle: 'Tubi in acciaio inossidabile per progetti industriali',
    introP1: 'Aceros è produttore brasiliano di acciai inossidabili centrifugati. Non commercializziamo tubi standard né commodity: la nostra fabbrica produce per centrifugazione su misura in leghe speciali resistenti a calore, abrasione e ossidazione severa (ASTM A297).',
    introP2: 'La centrifugazione favorisce una struttura densa e il controllo della geometria tubolare. Ogni progetto viene analizzato dall\'ingegneria affinché lega, dimensioni e finitura corrispondano alle condizioni operative indicate dal cliente.',
    introImgAlt: 'Tubo centrifugato in lega alta in fase di lavorazione',
    specsTitle: 'Specifiche tecniche', specsCol1: 'Categoria', specsCol2: 'Dettagli disponibili',
    specRows: [
      ['Leghe disponibili', 'Leghe speciali selezionate per applicazione, inclusi materiali secondo ASTM A297 se applicabili'],
      ['Processo produttivo', 'Fusione centrifugata e statica'],
      ['Fasi di finitura', 'Grezzo di centrifugazione, lavorato (perno), lucidato/finito o misto'],
      ['Dimensioni', 'Diametri, spessori e lunghezze 100% su misura'],
      ['Norme tecniche', 'ABNT, ASTM, DIN, AISI'],
      ['Ispezione', 'Tracciabilità e prove definite per la fornitura, comprese durezza, analisi chimica e ultrasuoni se applicabili'],
    ],
    specsFooter: 'Consulta il nostro team tecnico per specifiche in linea con la tua esigenza.',
    differentialsTitle: 'Vantaggi Aceros nei tubi',
    differentials: [
      { title: 'Fabbricazione su misura', text: 'Geometrie, dimensioni e finitura secondo il disegno tecnico.' },
      { title: 'Selezione delle leghe', text: 'Materiale definito in base a temperatura, abrasione, corrosione e condizioni di servizio.' },
      { title: 'Applicazioni ad alta temperatura', text: 'Tubi sviluppati per forni e processi termici industriali.' },
      { title: 'Processo di centrifugazione', text: 'Processo che favorisce maggiore densità strutturale e concentricità del tubo.' },
      { title: 'Gestione della qualità', text: 'Sistema di Gestione Qualità certificato secondo ISO 9001:2015.' },
      { title: 'Progetto per la condizione di servizio', text: 'Parametri di produzione valutati in base ai requisiti indicati dal cliente.' },
      { title: 'Lavorazione su disegno', text: 'Finitura e tolleranze dimensionali definite dal progetto.' },
      { title: 'Brasile ed estero', text: 'Servizio commerciale per progetti nazionali e internazionali.' },
      { title: 'Ingegneria dei materiali', text: 'Supporto tecnico per selezionare la lega adeguata.' },
    ],
    applicationsTitle: 'Settori serviti',
    applicationsLead: 'Applicazioni servite secondo disegno e requisiti operativi.',
    applicationLabels: ['Siderurgia', 'Mineraria', 'Trattamento termico', 'Zincatura', 'Industria della ghisa', 'Navale', 'Metallurgia'],
    galleryTitle: 'Galleria tecnica ed evoluzione della finitura',
    galleryLead: 'Dal grezzo di centrifugazione al pezzo lucidato: la qualità Aceros a ogni fase.',
    zoomAria: 'Ingrandisci',
    galleryAlts: [
      'Tubo centrifugato grezzo, appena uscito dalla fusione',
      'Tubo grezzo pronto per la lavorazione',
      'Tubo dopo la lavorazione CNC di precisione',
      'Tubo lavorato al perno',
      'Tubo lavorato e lucidato, finito con rinvenimento',
      'Tubo lucidato a specchio',
      'Tubo in ispezione dimensionale',
      'Tubo con finitura mista (lavorato + lucidato)',
    ],
    processTitle: 'Processo di fabbricazione',
    processSteps: [
      { title: 'Ricezione del progetto', desc: 'Analisi dei requisiti dimensionali e operativi.' },
      { title: 'Analisi tecnica', desc: 'La nostra ingegneria conferma la fattibilità.' },
      { title: 'Definizione della lega', desc: 'Selezione del materiale in base alle condizioni di servizio e alla norma applicabile.' },
      { title: 'Processo di fabbricazione', desc: 'Centrifugazione del grezzo con parametri definiti per diametro e massa.' },
      { title: 'Controllo dimensionale', desc: 'Misura precisa per garantire le tolleranze del progetto.' },
      { title: 'Ispezione di qualità', desc: 'Prove e verifiche definite secondo i requisiti della fornitura.' },
      { title: 'Consegna', desc: 'Spedizione protetta per industrie in tutto il Brasile.' },
    ],
    isoBadge: 'Certificazione internazionale',
    isoTitle1: 'ISO 9001:2015 ', isoTitleAccent: 'certificata',
    isoLead: 'Il nostro Sistema di Gestione della Qualità è certificato DQS GmbH, con accreditamento DAkkS e riconoscimento della rete IQNet.',
    isoCertLabel: 'Certificato', isoValidLabel: 'Valido fino al',
    isoFooter: 'Secondo i requisiti della fornitura, la documentazione può includere tracciabilità, rapporto metallurgico, prove di durezza, analisi chimica e ultrasuoni.',
    ctaMidTitle: 'Ti servono tubi in acciaio inossidabile?',
    ctaMidLead: 'Il nostro team tecnico valuta disegno e condizioni di servizio per orientare i prossimi passi del progetto.',
    ctaMidRequest: 'Richiedi preventivo', ctaMidWhatsapp: 'Invia progetto via WhatsApp',
    faqTitle: 'Domande frequenti',
    faqs: [
      { q: 'Quali vantaggi offrono i tubi centrifugati di Aceros?', a: 'A differenza dei tubi standard, i nostri sono realizzati su misura. Il processo favorisce una struttura densa e permette di definire dimensioni, lega e finitura in base all\'applicazione industriale.' },
      { q: 'Quali fasi di finitura offrite?', a: 'Quattro fasi in base al progetto: 1. Grezzo di centrifugazione (alta densità); 2. Lavorato (perno e corpo satinato); 3. Lucidato/finito (superficie a specchio con rinvenimento); 4. Misto (su richiesta).' },
      { q: 'Aceros tratta commodity?', a: 'No. Siamo una fabbrica focalizzata esclusivamente su ingegneria e produzione su misura di componenti in lega alta centrifugati e lavorati su disegno.' },
      { q: 'Quali dimensioni e leghe sono disponibili?', a: 'La lega è selezionata in base a temperatura, abrasione, corrosione e condizioni di servizio. Diametro, spessore e lunghezza sono definiti dal disegno di progetto.' },
      { q: 'Servite ordini per Brasile ed estero?', a: 'Sì. Serviamo progetti in Brasile e all\'estero. Condizioni di consegna e tempi sono confermati nell\'offerta commerciale.' },
    ],
    formTitle: 'Richiedi il tuo preventivo di tubi',
    formLead1: 'Il nostro team tecnico analizza le informazioni del progetto e prepara l\'offerta.',
    formLead2: 'Risposta commerciale entro un giorno lavorativo.',
    formName: 'Nome completo', formNamePh: 'Il tuo nome',
    formCompany: 'Azienda', formCompanyPh: 'Nome azienda',
    formPhone: 'Telefono / WhatsApp',
    formCity: 'Città / Provincia', formCityPh: 'Città - Provincia',
    formEmail: 'E-mail aziendale', formEmailPh: 'email@azienda.it',
    formMaterial: 'Lega o materiale', formMaterialPh: 'Se noto',
    formDeadline: 'Tempo di consegna', formDeadlinePh: 'Es.: 60 giorni',
    formDimensions: 'Dimensioni e quantità', formDimensionsPh: 'Diametro, spessore, lunghezza e quantità',
    formDrawing: 'Disegno tecnico', formDrawingHelp: 'PDF, DWG, DXF, STEP, IGES, JPG o PNG, fino a 5 MB.',
    formMessage: 'Informazioni aggiuntive', formMessagePh: 'Indica applicazione, temperatura e altre condizioni operative.',
    formPrivacyA: 'Ho letto e accetto l\'', formPrivacyLink: 'Informativa sulla privacy', formPrivacyB: ' e autorizzo l\'uso dei dati per rispondere a questa richiesta.',
    formSubmitting: 'Invio in corso...', formSubmit: 'Richiedi preventivo',
    toastOkTitle: 'Richiesta inviata!', toastOkDesc: 'Il tuo messaggio è stato inviato. Il nostro team ti contatterà a breve.',
    toastErrTitle: 'Invio non riuscito', toastErrDesc: 'Riprova o scrivici su WhatsApp per accelerare il preventivo.',
    whatsappMessage: 'Ciao! Vorrei richiedere un preventivo per tubi in acciaio inossidabile.',
    heroImgAlt: 'Tubo in acciaio inossidabile centrifugato, lavorato e lucidato di Aceros',
  },
};
